### ISSUE TITLE
viewWillAppear transition

### ISSUE THREAD

**Issue by piercifani** [jessesquires/JSQMessagesViewController#1102] opened 2015-07-21 14:01 UTC
When loading the JSQMessagesViewController with a dataSource of ~150 messages (or any number of messages that make the `contenteSize.height` bigger than the frame's height), the transition is glitchy when pushing it onto the navigation stack.

If, however, I remove the `dispatch_async` section of the `viewWillAppear` method in JSQMessagesViewController.m:231 and make the scroll to bottom method call synchronous, the transition is perfect.

Is there a reason why this method is defined asynchronous instead of synchronous?

All the best

**Comment by jessesquires** [comment] 2015-07-22 02:33
hey @piercifani - this is a hack, see #256 for the history.

**Comment by jessesquires** [comment] 2015-07-22 02:34
if you think `dispatch_async` is no longer necessary, please provide more info. (library version, iOS version, repro steps, etc)

**Comment by piercifani** [comment] 2015-07-22 14:38
Seems like the core issue (that the layout is not completed in `viewWillAppear`) can be fixed by making the necessary calls in `viewDidLayoutSubviews` instead.

I moved relevant stuff from the former to the latter, now they look like this:

```
- (void)viewWillAppear:(BOOL)animated
{
    NSParameterAssert(self.senderId != nil);
    NSParameterAssert(self.senderDisplayName != nil);

    [super viewWillAppear:animated];
    [self.view layoutIfNeeded];
}

- (void)viewDidLayoutSubviews
{
    [super viewDidLayoutSubviews];
    
    [self.collectionView.collectionViewLayout invalidateLayout];
    
    if (self.automaticallyScrollsToMostRecentMessage) {
        [self scrollToBottomAnimated:NO];
        [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
    }
    
    [self jsq_updateKeyboardTriggerPoint];
}
```

This seems to work well on iOS8, latest library version. No more glitches when pushing a JSQMessageVC with lots of messages into the navigation stack, and no more weird behavior if there are few messages on the controller.

Let me know if you think this is appropriate to merge.

**Comment by jessesquires** [comment] 2015-07-23 05:11
Thanks @piercifani 

We definitely *do not* want to do this though. This code will execute **every time** the view does a layout — definitely not the behavior that we want. It might even cause an infinite loop since invalidating the layout implicitly triggers a new layout pass.

**Comment by piercifani** [comment] 2015-07-23 19:54
mmm, you're completely right, this kills performance... I'll try a different approach and get back with you

**Comment by jessesquires** [comment] 2015-07-24 03:33
:+1: :smile:

**Comment by jessesquires** [comment] 2015-07-24 03:38
hey @piercifani - just realized that this is a dupe of #780. let's move over there to continue the conversation.

**Closed by jessesquires** 2015-07-24 03:38 UTC
Labels: bug, duplicate
