### ISSUE TITLE
JSQMessagesComposerTextView not flexible to text inside

### ISSUE THREAD

**Issue by NidhiJoshi7** [jessesquires/JSQMessagesViewController#1567] opened 2016-05-08 11:43 UTC
## Question 
 I am using JSQMessagesViewController for chat view in my project. I am using swift. While message is small like.. "Hi","R u there?" I looks fine.. but when it's long enough of 5 words or more than that.. it's just showing starting 2-3 words.. that's all... if I copy that message it has the whole message... but not showing that in bubble... I have read another Question similar to this is https://github.com/jessesquires/JSQMessagesViewController/issues/846

But i don't found it helpful. Can you please help me to solve this... thanks in advance

**Comment by jessesquires** [comment] 2016-05-26 03:26
Thanks @NidhiJoshi7 ! 😄 

This sounds like a duplicate of #1034. Please check that and let us know if your issues is fixed.

**Closed by jessesquires** 2016-05-26 03:26 UTC
Labels: questions & help
