### ISSUE TITLE
Error with Swift 1.2 Xcode 6.3

### ISSUE THREAD

**Issue by mrazam110** [jessesquires/JSQMessagesViewController#1064] opened 2015-07-01 11:00 UTC
![screen shot 2015-07-01 at 10 16 12 am](https://cloud.githubusercontent.com/assets/5674070/8453061/4597558a-200a-11e5-81a1-6ff6836ed93f.png)
I am using swift 1.2 Xcode 6.3

**Comment by mrazam110** [comment] 2015-07-01 11:01
It is working perfectly with Xcode 6.2 but on 6.3 it is not working

**Comment by jessesquires** [comment] 2015-07-01 15:28
dupe of #918

please check existing issues before opening new ones. i put forth a lot of effort to keep issues organized and labeled appropriately.

**Closed by jessesquires** 2015-07-01 15:28 UTC
Labels: bug, duplicate, swift support
