### ISSUE TITLE
Double-tap on textViews shows "copy/define" menu if selectable == YES

### ISSUE THREAD

**Issue by BruceZCQ** [jessesquires/JSQMessagesViewController#747] opened 2015-01-20 07:22 UTC
double tap cell, show menu,choose "copy" will crash

**Comment by jessesquires** [comment] 2015-01-20 17:16
duplicate of #591 -- please comment there.

**Comment by jessesquires** [comment] 2015-01-21 07:33
Re-opening this issue as "an official duplicate" of #591 to track the issue here instead of on #591 .

I think we have no option but to use [TTTAttributedLabel](https://github.com/TTTAttributedLabel/TTTAttributedLabel) at this point.

But, this will also help with #492

**Comment by BruceZCQ** [comment] 2015-01-21 07:52
Thanks @jessesquires, JSQMessagesViewController let my project more smoothly.I will use JSQMessagesViewController JSQLocationMediaItem JSQVideoMediaItem, JSQPhotoMediaItem. Perhaps can have JSQVoiceMediaItem like WeChat 's voice. ☺️

**Comment by jessesquires** [comment] 2017-07-17 02:34
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:34 UTC
Labels: bug, duplicate, priority: high
