### ISSUE TITLE
I am adding an media Item in chat messages but getting this layout issue.

### ISSUE THREAD

**Issue by niteshtak** [jessesquires/JSQMessagesViewController#1698] opened 2016-06-27 11:21 UTC
## New issue checklist

- [ ] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

### General information

- Library version(s):
- iOS version(s):
- Devices/Simulators affected:
- Reproducible in the demo project? (Yes/No): 
- Related issues:

#### Expected behavior

> ...

#### Actual behavior

> ...

#### Steps to reproduce

> ...

#### Crash log? Screenshots? Videos? Sample project?

>...

## Question or Feature Request

> ...

**Comment by jessesquires** [comment] 2016-06-27 14:42
@niteshtak please do not open duplicate issues. 

dupe of #1698

**Closed by jessesquires** 2016-06-27 14:42 UTC
Labels: invalid
