### ISSUE TITLE
Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by etayluz** [jessesquires/JSQMessagesViewController#1085] opened 2015-07-13 17:24 UTC
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1790e580 V:[JSQMessagesLabel:0x166dc9d0(20)]>",
    "<NSLayoutConstraint:0x166dd950 V:[JSQMessagesLabel:0x166dd740(20)]>",
    "<NSLayoutConstraint:0x166e16c0 V:[JSQMessagesCellTextView:0x16ba8400]-(0)-|   (Names: '|':UIView:0x166ddcd0 )>",
    "<NSLayoutConstraint:0x166e1720 V:|-(0)-[JSQMessagesCellTextView:0x16ba8400]   (Names: '|':UIView:0x166ddcd0 )>",
    "<NSLayoutConstraint:0x166e1dd0 V:[JSQMessagesLabel:0x166e1c50(0)]>",
    "<NSLayoutConstraint:0x166e2250 V:|-(0)-[JSQMessagesLabel:0x166dc9d0]   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e22e0 V:[JSQMessagesLabel:0x166dc9d0]-(0)-[JSQMessagesLabel:0x166dd740]>",
    "<NSLayoutConstraint:0x166e2340 V:[JSQMessagesLabel:0x166dd740]-(0)-[UIView:0x166ddcd0]>",
    "<NSLayoutConstraint:0x166e2430 V:[JSQMessagesLabel:0x166e1c50]-(0)-|   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e2460 V:[UIView:0x166ddcd0]-(0)-[JSQMessagesLabel:0x166e1c50]>",
    "<NSAutoresizingMaskLayoutConstraint:0x179d6430 h=--& v=--& V:[UIView:0x166db190(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x166e16c0 V:[JSQMessagesCellTextView:0x16ba8400]-(0)-|   (Names: '|':UIView:0x166ddcd0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-07-13 12:23:13.151 RoomApp[1457:450345] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1790e580 V:[JSQMessagesLabel:0x166dc9d0(20)]>",
    "<NSLayoutConstraint:0x166dd950 V:[JSQMessagesLabel:0x166dd740(20)]>",
    "<NSLayoutConstraint:0x166e1600 V:[UIImageView:0x166ddd90]-(0)-|   (Names: '|':UIView:0x166ddcd0 )>",
    "<NSLayoutConstraint:0x166e1660 V:|-(0)-[UIImageView:0x166ddd90]   (Names: '|':UIView:0x166ddcd0 )>",
    "<NSLayoutConstraint:0x166e1dd0 V:[JSQMessagesLabel:0x166e1c50(0)]>",
    "<NSLayoutConstraint:0x166e2250 V:|-(0)-[JSQMessagesLabel:0x166dc9d0]   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e22e0 V:[JSQMessagesLabel:0x166dc9d0]-(0)-[JSQMessagesLabel:0x166dd740]>",
    "<NSLayoutConstraint:0x166e2340 V:[JSQMessagesLabel:0x166dd740]-(0)-[UIView:0x166ddcd0]>",
    "<NSLayoutConstraint:0x166e2430 V:[JSQMessagesLabel:0x166e1c50]-(0)-|   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e2460 V:[UIView:0x166ddcd0]-(0)-[JSQMessagesLabel:0x166e1c50]>",
    "<NSAutoresizingMaskLayoutConstraint:0x179d6430 h=--& v=--& V:[UIView:0x166db190(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x166e1600 V:[UIImageView:0x166ddd90]-(0)-|   (Names: '|':UIView:0x166ddcd0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-07-13 12:23:13.155 RoomApp[1457:450345] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x1790e580 V:[JSQMessagesLabel:0x166dc9d0(20)]>",
    "<NSLayoutConstraint:0x166dd950 V:[JSQMessagesLabel:0x166dd740(20)]>",
    "<NSLayoutConstraint:0x166e1dd0 V:[JSQMessagesLabel:0x166e1c50(0)]>",
    "<NSLayoutConstraint:0x166e2250 V:|-(0)-[JSQMessagesLabel:0x166dc9d0]   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e22e0 V:[JSQMessagesLabel:0x166dc9d0]-(0)-[JSQMessagesLabel:0x166dd740]>",
    "<NSLayoutConstraint:0x166e2340 V:[JSQMessagesLabel:0x166dd740]-(0)-[UIView:0x166ddcd0]>",
    "<NSLayoutConstraint:0x166e2430 V:[JSQMessagesLabel:0x166e1c50]-(0)-|   (Names: '|':UIView:0x166db190 )>",
    "<NSLayoutConstraint:0x166e2460 V:[UIView:0x166ddcd0]-(0)-[JSQMessagesLabel:0x166e1c50]>",
    "<NSAutoresizingMaskLayoutConstraint:0x179d6430 h=--& v=--& V:[UIView:0x166db190(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x166dd950 V:[JSQMessagesLabel:0x166dd740(20)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-07-13 12:23:13.685 RoomApp[1457:450345] Error Domain=Ooops! Code=0 "The operation couldn’t be completed. (Ooops! error 0.)" UserInfo=0x17d1adc0 {errors=Internet connection interrupted. Please try again when re-connected.}

**Comment by jessesquires** [comment] 2015-07-14 02:43
this doesn't look related to JSQMessages, but if it is, it's a dupe of #817

**Closed by jessesquires** 2015-07-14 02:43 UTC
