### ISSUE TITLE
'JSQMessagesBubbleImageFactory.Type' does not have a member named  'outgoingMessageBubbleImageViewWithColor'/'incomingMessageBubbleImageViewWithColor'

### ISSUE THREAD

**Issue by datomnurdin** [jessesquires/JSQMessagesViewController#852] opened 2015-03-10 16:47 UTC
I'm using swift right now. What I'm facing now is I got this error message when trying initialize ```outgoingBubbleImageView``` and ```incomingBubbleImageView```

```
'JSQMessagesBubbleImageFactory.Type' does not have a member named 'incomingMessageBubbleImageViewWithColor'

'JSQMessagesBubbleImageFactory.Type' does not have a member named 'outgoingMessageBubbleImageViewWithColor'
```

My code
```
var outgoingBubbleImageView = JSQMessagesBubbleImageFactory.outgoingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleLightGrayColor())
    var incomingBubbleImageView = JSQMessagesBubbleImageFactory.incomingMessageBubbleImageViewWithColor(UIColor.jsq_messageBubbleGreenColor())
```

After I change it to this one, I got latest error message

```
var outgoingBubbleImageView = JSQMessagesBubbleImageFactory.outgoingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleLightGrayColor())
    var incomingBubbleImageView = JSQMessagesBubbleImageFactory.incomingMessagesBubbleImageWithColor(UIColor.jsq_messageBubbleGreenColor())
```

error message
```
'UIColor' is not convertible to 'JSQMessagesBubbleImageFactory'
```

**Comment by jessesquires** [comment] 2015-03-10 17:25
duplicate of #629

**Closed** 2015-03-16 21:38 UTC
Labels: duplicate, questions & help, swift support
