### ISSUE TITLE
Auto property synthesis will not synthesize property 'collectionView'; it will be implemented by its superclass, use @dynamic to acknowledge intention

### ISSUE THREAD

**Issue by datomnurdin** [jessesquires/JSQMessagesViewController#962] opened 2015-05-05 13:28 UTC
I got this warning message after update latest pod.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/Headers/Private/JSQMessagesViewController/JSQMessagesCollectionViewFlowLayout.h:59:60: Auto property synthesis will not synthesize property 'collectionView'; it will be implemented by its superclass, use @dynamic to acknowledge intention
```

Code

```
@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;
```

Please advice. Thank you

**Comment by jessesquires** [comment] 2015-05-05 14:59
fixed in 7.0.1. duplicate of #828 

please do not open duplicate issues.

**Closed by jessesquires** 2015-05-05 14:59 UTC
