### ISSUE TITLE
When begin typing ,the last message in collectionView just show a half ,please check the picture i upload.

### ISSUE THREAD

**Issue by vedon** [jessesquires/JSQMessagesViewController#903] opened 2015-04-01 07:21 UTC
![screen shot 2015-04-01 at 3 18 16 pm](https://cloud.githubusercontent.com/assets/1811570/6936272/cc206e0e-d882-11e4-9219-8e1f60bf2776.png)

**Comment by jessesquires** [comment] 2015-04-01 15:53
duplicate of #450

**Closed by jessesquires** 2015-04-01 15:53 UTC
