### ISSUE TITLE
Keyboard trigger point not updated when reusing view

### ISSUE THREAD

**Issue by chrisballinger** [jessesquires/JSQMessagesViewController#941] opened 2015-04-22 00:46 UTC
When reusing an instance of JSQMessagesViewController the keyboard trigger point doesn't seem to be updated properly after showing the view a second time.

Added reused messages view controller to demo project here:  https://github.com/ChatSecure/JSQMessagesViewController/tree/7.0.1-reuse_toolbar_bug

Steps to reproduce:
1. Press "Push reused programatically" after launching JSQMessages demo project
2. Tap the "New Message" text field area to bring up the keyboard
3. Press Back button
4. Press  "Push reused programatically" again
5. Try to dismiss keyboard by activating trigger point

You'll notice that the trigger point is set as if the toolbar was still at the bottom of the screen. I believe this is because when `jsq_updateKeyboardTriggerPoint` is called in viewWillAppear, the inputToolbar is momentarily at the bottom of the screen. The text field is the first responder so the keyboard appears, changing the location of the inputToolbar but not the trigger point. I've also noticed a related bug where the inputToolbar stays underneath the keyboard indefinitely.

I tried merging the pull requests from @erysaj to see if they fixed the problem, but it actually made the problem worse.

I'll update this issue when I come up with a non-hacky fix.

**Comment by jessesquires** [comment] 2015-04-22 02:05
thanks @chrisballinger !

**Comment by walsh2000** [comment] 2015-04-22 04:56
> I've also noticed a related bug where the inputToolbar stays underneath the keyboard indefinitely.

I'm looking into something just like this in my JSQ-based app. I push a VC onto the NavigationController, rather than reuse the JSQ. If the keyboard was up when I pushed the 2nd VC, the toolbar is stuck under the keyboard when I pop that 2nd VC off of the NavController.

My first thought was there might be a race between subscribing to notifications vs when we trigger becomeFirstResponder, but I will definitely look into the trigger point angle as well now.

**Comment by erysaj** [comment] 2015-04-22 14:47
@chrisballinger 
> I've also noticed a related bug where the inputToolbar stays underneath the keyboard indefinitely.

How to reproduce that bug?

I've tried out your demo.
After applying my PRs, instead of non-working "drag-to-dismiss-keyboard" we have a keyboard without toolbar on top of it. I've been able to fix that by moving `[self.keyboardController beginListeningForKeyboard];` from `-[JSQMessagesViewController viewDidAppear:]` to `-[JSQMessagesViewController viewWillAppear:`] (text view remains the first responder, so during push transition keyboard appears and corresponding notifications are posted, but keyboard controller is not listening to them yet so toolbar position is not updated properly ). I suppose I'll just add this change to my PR #907

Besides, I guess your issue might be also helped by dismissing keyboard when leaving the chat (without any changes to the library).

**Comment by walsh2000** [comment] 2015-04-22 16:25
> How to reproduce that bug?

In my case, I push another VC onto the navigation VC (back will take you back to the JSQ VC).
When you push the new VC while the keyboard is showing, the toolbar is hidden behind the keyboard when we pop that 2nd VC... Only on the device. In the simulator the toolbar lazily animates up about 1 second later.


>I've been able to fix that by moving [self.keyboardController beginListeningForKeyboard]; from -[JSQMessagesViewController viewDidAppear:] to -[JSQMessagesViewController viewWillAppear:] 

This fits with my initial thoughts that this might be a race between the keyboard showing and the JSQ subscribing to the notifications, but I haven't yet investigated this particular bug.

> Besides, I guess your issue might be also helped by dismissing keyboard when leaving the chat (without any changes to the library).

For sure. I will investigate that angle too.

Thank you

**Comment by chrisballinger** [comment] 2015-04-22 22:25
Adding `[self.inputToolbar.contentView.textView resignFirstResponder];` to my `viewWillDisappear` method seemed to fix the original issue without changing the internals of JSQ. After this change I also haven't been able to reproduce the issue where the inputToolbar was hiding behind the keyboard, although that issue was very sporadic and hard to reproduce. Haven't tested against @erysaj's new PR.

@jessesquires Would it make sense to add resignFirstResponder to viewWillDisappear in JSQMessagesViewController.m?

**Comment by erysaj** [comment] 2015-04-22 23:05
@chrisballinger 
FYI, you can dismiss keyboard much easier: `[self.view endEditing:YES];`
I'd probably add that code into demo project as an example and let library user decide if he needs that functionality in own JSQMessagesViewController subclass OR even add a setting to enable/disable this snippet

@walsh2000 I have missed your reproduce scenario. I will take a look

**Comment by walsh2000** [comment] 2015-04-24 00:08
@erysaj 
Thank you.

To be clear I am not reporting any problems with your PR. I jumped in on this issue because I noticed it had similarities with another issue I was tracking (but which I had not reported here because I assumed it was in my code base)

**Comment by chrisballinger** [comment] 2015-05-06 00:15
Although the issue is much harder to reproduce when manually dismissing the keyboard, I just noticed it again, so it isn't a full fix for the issue.

**Comment by jessesquires** [comment] 2016-05-30 22:12
Fixed by 752fd38aa8b899cbe2e21b6595de58920977bfc2

**Closed by jessesquires** 2016-05-30 22:12 UTC
Labels: bug
