### ISSUE TITLE
How to add UITapGestureRecognizer - Tapping outside does not dismiss keyboard

### ISSUE THREAD

**Issue by hmaidasani** [jessesquires/JSQMessagesViewController#1135] opened 2015-08-03 07:06 UTC
Hey @jessesquires, I'm having the same issue as @sahirc in #1076. The collectionView tap gestures don't get recognized everywhere. A simple tap outside the keyboard does not dismiss it. Below is the code which has been adapted from issue #360. Any suggestions?

```
import UIKit
import Foundation

class ChatViewController: JSQMessagesViewController, UIGestureRecognizerDelegate {

...
...

   override func viewDidLoad() {
        super.viewDidLoad()
        ...
        addTapGestures()
        ...
   }

   func gestureRecognizer(UIGestureRecognizer,
        shouldRecognizeSimultaneouslyWithGestureRecognizer:UIGestureRecognizer) -> Bool {
            return true
   }

   func addTapGestures() {
        let gesture = UITapGestureRecognizer(target: self, action: Selector("tapAndHideKeyboard:"))
        self.collectionView.addGestureRecognizer(gesture)
   }

   func tapAndHideKeyboard(gesture: UITapGestureRecognizer) {
        println(gesture)
        if(gesture.state == UIGestureRecognizerState.Ended) {
            if(self.inputToolbar.contentView.textView.isFirstResponder()) {
                self.inputToolbar.contentView.textView.resignFirstResponder()
            }
        }
   }

...

}
```

**Comment by jessesquires** [comment] 2015-08-03 14:10
Thanks @hmaidasani ! I'm going to close this as a duplicate of #1076. The issue may be closed, but the discussion can still continue there :smile: 

> P.S. Please review the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md) before opening new issues! :smile:

**Closed by jessesquires** 2015-08-03 14:10 UTC
Labels: duplicate, questions & help
