### ISSUE TITLE
Keyboard dragging to close does not work on iOS9 as expected

### ISSUE THREAD

**Issue by kostub** [jessesquires/JSQMessagesViewController#1181] opened 2015-08-27 18:41 UTC
To reproduce:
1. Build the app by linking to the iOS8 SDK.
2. On an ios9 device, open the chat and tap on the message box for the keyboard to show up.
3. Drag the message bar down to close the keyboard.

As expected the message bar moves down, however the keyboard does not move down with it.
Once you release your finger the keyboard closes.

Expected:
The keyboard moves along with the message bar and you can drag it up and down similar to how it works in iOS8.

**Comment by jessesquires** [comment] 2015-08-28 03:38
duplicate of #1063

**Closed by jessesquires** 2015-08-28 03:38 UTC
Labels: bug, duplicate, iOS beta
