### ISSUE TITLE
Respect language direction -- Fix leading/trailing vs left/right constraints for i18n

### ISSUE THREAD

**Issue by khaledalissa** [jessesquires/JSQMessagesViewController#1101] opened 2015-07-21 13:59 UTC
When the phone is set to an RTL language, the whole interface is flipped: incoming messages show up on the right of the screen and outgoing on the left. However, that is not the norm set by famous chat applications. For example, the interface of iMessage and WhatsApp treat the layout the same way regardless of language direction.

**Comment by jessesquires** [comment] 2015-07-22 01:59
Thanks @khaledalissa!

Please provide more information, I'm not sure I know what you're talking about. :smile: 

Also, please provide the following:

1. Library version 
2. iOS version
3. Devices / simulators
4. Full crash log
5. Steps to reproduce
6. List any possible related existing issues

**Comment by khaledalissa** [comment] 2015-07-22 18:07
1. Library version: 7.1.0
2. iOS version: 8.3
3. Simulator: iPhone 6
4. No crash Log
5. Steps to reproduce: change device language to RTL language ( tested with Arabic)  
6.  Issue #611 shows the same problem. 

HOWEVER, I just reinstalled it and everything worked well :smile: I don't really know what caused the issue.  
Thanks for your quick reply and the amazing work!

It used to look like this.
![screen shot](https://cloud.githubusercontent.com/assets/1767899/8829260/4c9e03ac-309e-11e5-8b6b-3c2c0a5413e9.png)

**Comment by khaledalissa** [comment] 2015-07-22 18:18
It looks like the RTL-language localization folder (ar.lproj) was triggering the layout to be flipped. Once I deleted it, it all worked well. Is there a way to stop the layout from reacting to the localization folder?

**Comment by jessesquires** [comment] 2015-07-23 05:16
Thanks @khaledalissa ! :smile: 

>It looks like the RTL-language localization folder (ar.lproj) was causing the layout to be flipped. Once I deleted it, it all worked well. Is there a way to stop the layout from reacting to the localization folder?

Can you explain this more?

**Comment by khaledalissa** [comment] 2015-07-23 06:47
I used to have a folder called ar.lproj that is responsible for localizing the app into Arabic. The presence of this folder causes the layout of JSQMessagesViewController to be flipped. (right becomes left). After deleting the folder, the device language did not have any effect on the layout of JSQMessagesViewController. So I was wondering if there is a way to stop JSQMessagesViewController from reacting to the presence of this folder.  Hope it's more clear this time :smile:

**Comment by jessesquires** [comment] 2015-07-23 15:42
Hm... is this the same as #713? Can you post screenshots of before and after, and a demo project that shows the issue?

**Comment by khaledalissa** [comment] 2015-07-24 12:12
I believe [This comment](https://github.com/jessesquires/JSQMessagesViewController/issues/611#issuecomment-75044005) under issue #611  is the one similar to the issue I'm having. I have [forked and updated the demo project you provide to demonstrate the behavior](https://github.com/khaledalissa/JSQMessagesViewController/tree/RTL_DEMO).

Here are the steps I made that causes this behavior: 
1. created **ar.lproj**
2. added support for Arabic by adding the value **"ar"** to the **CFBundleLocalizations** property through Info tab in Xcode.

#### When Arabic:
![arabic](https://cloud.githubusercontent.com/assets/1767899/8873983/eb76b06a-3214-11e5-85c0-ecc149d217df.png)

#### When English
![english](https://cloud.githubusercontent.com/assets/1767899/8873988/f8f44554-3214-11e5-9b4c-7372c627e308.png)

**Comment by hasbean** [comment] 2015-07-30 06:22
I forked the repo and removed the Leading/Trailing constraints and instead used Left/Right to ignore language direction.

https://github.com/hasbean/JSQMessagesViewController

I'm not sure if this is the way to go, but it's working well for my case.

**Comment by khaledalissa** [comment] 2015-08-01 17:10
thanks @hasbean. that worked well.

**Comment by ebbe-brandstrup** [comment] 2015-10-26 08:31
yes, thanks @hasbean. Also works for me (note that it is the JSQMessagesCollectionViewCellIncoming.xib and JSQMessagesCollectionViewCellOutgoing.xib files you need to open as source and search/replace ```leading``` to ```left``` and ```trailing``` to ```right```.

**Comment by jerembab** [comment] 2016-10-13 07:03
Hi @khaledalissa , how did you manage to move to the right place (in RTL) the texts at the bottom and the top of the bubble.. I stuck with this issue #1859 
thanks for your help

**Comment by khaledalissa** [comment] 2016-10-14 07:00
@jerembab I've been using the fix done by @hasbean: https://github.com/hasbean/JSQMessagesViewController

**Comment by jerembab** [comment] 2016-10-14 13:38
@khaledalissa really thanks for answering , Im new at gitHub , how can I use the fixe done by @hasbean  ? update the JSQ pod?

**Comment by khaledalissa** [comment] 2016-10-15 13:18
@jerembab I think replacing the pod you currently have with this one will solve the problem. Keep i mind this might be an older version of the JSQ pod, so you might lose some functionality If you decide to use it.
```
pod 'JSQMessagesViewController', :git => 'https://github.com/hasbean/JSQMessagesViewController.git', :branch => 'develop'
```

**Comment by jessesquires** [comment] 2016-10-24 20:46
Related: #1859

**Comment by jessesquires** [comment] 2017-07-17 02:29
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:29 UTC
Labels: bug, priority: high
