### ISSUE TITLE
Resize JSQMessagesViewController frame on change of container view height

### ISSUE THREAD

**Issue by mohonish** [jessesquires/JSQMessagesViewController#1104] opened 2015-07-22 05:45 UTC
I have a JSQMessagesViewController inside a container view. The issue that I'm facing is that when the container view height is increased (with animation) for certain UI effects, the JSQMessages Collection View height does not resize to fit the container view frame.

Could you point me towards the right direction about what I should do to make the collectionView resize when the container view height changes? I'm using Swift.

**Update 1:**
I've set the following inside the container view controller class,

    self.view.autoresizingMask = UIViewAutoresizing.FlexibleHeight
    self.view.autoresizesSubviews = true
    self.collectionView.autoresizingMask = UIViewAutoresizing.FlexibleHeight
    self.collectionView.autoresizesSubviews = true

But this only resizes the view, and the JSQMessagesCollectionView is not resized the expand to the height of the parent view.

I'm attaching a screenshot of the view hierarchy. The selected view is the JSQMessagesCollectionView (as can be seen). The grey view below it is what is referred by `self.view` from inside the container view controller class. And the black view is the Container view.

![screen shot 2015-07-22 at 3 53 06 pm](https://cloud.githubusercontent.com/assets/6361604/8823365/e240f294-3089-11e5-8bb1-c11868da2ff2.png)

**Update 2:**
I set the following code inside the container view controller class

    override func viewDidLayoutSubviews() {
        self.collectionView.frame = self.view.frame
        //self.collectionView.setNeedsLayout()
        //self.collectionView.layoutIfNeeded()
        println("collectionview frame: \(self.collectionView.frame)")
        println("view frame: \(self.view.frame)")
    }

The collectionview frame is now being resized to the view frame, but the elements don't resize (the keyboard is not at the bottom). Enabling `setNeedsLayout()` and `layoutIfNeeded()` does not help as the collectionview again becomes smaller.

**Comment by gcarlo89** [comment] 2015-07-23 03:44
@mohonish I don't have the whole picture, but can you try overriding `updateViewConstraints` and setting the constraints programmatically:
```objective-c
-(void)updateViewConstraints{
    
    [super updateViewConstraints];
  
    [self.subView addConstraint:[NSLayoutConstraint constraintWithItem:self.subView
                                                                            attribute: NSLayoutAttributeTop
                                                                            relatedBy:NSLayoutRelationEqual
                                                                               toItem:self.containerView
                                                                            attribute: NSLayoutAttributeTop
                                                                           multiplier:1.0
                                                                             constant:0]];
        
    [self.subView addConstraint:[NSLayoutConstraint constraintWithItem:self.subView
                                                                          attribute: NSLayoutAttributeBottom
                                                                          relatedBy:NSLayoutRelationEqual
                                                                             toItem:self.containerView
                                                                          attribute: NSLayoutAttributeBottom
                                                                         multiplier:1.0
                                                                           constant:0]];
}
```
Test it out and tell me if it works. I don't really like doing it this way, it usually is better to set this type of constraints in the interface builder (I also prefer using this type of constraints vs autoresizing)

ps. sorry I didn't have the time to write it in Swift, but it should be pretty similar

**Comment by mohonish** [comment] 2015-07-23 04:28
@gcarlo89 that doesn't work. The collectionView doesn't resize yet. Tell me if you need any other details.

**Comment by jessesquires** [comment] 2015-07-23 05:19
Hey @mohonish — @gcarlo89 's suggestions are on the right track.

It sounds like this is an issue with your setup/configuration — not the library itself. I'm going to close this, but feel free to continue the conversation here. :smile:

**Closed by jessesquires** 2015-07-23 05:19 UTC
Labels: questions & help

**Comment by mohamedalsherif** [comment] 2016-01-18 18:04
any solution?

**Comment by MurLuck** [comment] 2016-01-19 15:19
can you show the complete class of the chat room

**Comment by mohamedalsherif** [comment] 2016-01-19 22:49
My code is maybe different from the O.P. although we have the same problem.

I need to able to change the height of the content view of the Collection View.

I am extending a Messages View Controller. I will show you my code to the bare minimum for the updateViewConstraints solution.
```objective-c
#import <JSQMessagesViewController/JSQMessagesViewController.h>
@interface JSQMessagesViewControllerExtended : JSQMessagesViewController

@end
```

```objective-c
#import "JSQMessagesViewControllerExtended.h"
@interface JSQMessagesViewControllerExtended ()
@end

@implementation JSQMessagesViewControllerExtended

-(void)updateViewConstraints{
    
    [super updateViewConstraints];
  
    NSLayoutConstraint *centeringConstraint =
    [NSLayoutConstraint constraintWithItem:self.collectionView
                                 attribute:NSLayoutAttributeBottom
                                 relatedBy:NSLayoutRelationEqual
                                    toItem:self.inputToolbar
                                 attribute:NSLayoutAttributeTop
                                multiplier:1.0
                                  constant:250];
    
    centeringConstraint.priority = 1000;
    [self.view addConstraint:centeringConstraint];
}
@end
```
The situation here looks like this : 

 
![iphone6](https://cloud.githubusercontent.com/assets/2623197/12433966/997e5ae4-bf0c-11e5-99d6-854aac04a1e8.png)


As you can see the blue bubbles are still continuing under the toolbar. What I want instead is that the content size (or the frame size) of the collection View is smaller.


The other solution with the didLayout subviews leads to a vc that looks like this:
![iphone62](https://cloud.githubusercontent.com/assets/2623197/12434354/e32bb64e-bf0e-11e5-8a86-001f15e465c5.png)

This is actually exactly what I need the VC to look like. But the problem is that if I touch the textarea . The keyboard pops up and then it looks like this:
![iphone3](https://cloud.githubusercontent.com/assets/2623197/12434390/1557e23c-bf0f-11e5-8b2c-132df009ff60.png)

Also some weird animation is happening during the time that the keyboard slides open.

To your question about nav/tabbar controllers (if that helps)
I am inside a navigation controller that is inside a tabbarcontroller.

**Comment by Reminouche** [comment] 2016-04-10 17:21
Any new solutions ?

**Comment by rrphenix** [comment] 2016-04-11 22:57
Did anyone ever arrive at a solution for this?
