### ISSUE TITLE
'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle:

### ISSUE THREAD

**Issue by ianstephens** [jessesquires/JSQMessagesViewController#1875] opened 2016-10-19 03:22 UTC
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
## General information
- Library version(s): 7.3.4
- iOS version(s): 10.0
- Devices/Simulators affected: iPhone SE
- Reproducible in the demo project? (Yes/No): 
- Related issues:
## What happened?

So I'm using objc combined with swift.
I'm calling a segue from objc:

``` objc
-(void) tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath
{
    index = indexPath.row;
    [tableView deselectRowAtIndexPath:indexPath animated:YES];
    [self performSegueWithIdentifier:@"ChatToDetail" sender:NULL];
}

- (void)prepareForSegue:(UIStoryboardSegue *)segue sender:(id)sender {
    ChatViewController *c = segue.destinationViewController;
    c.senderIDswift = currentPhone;
    c.chatIDswift = _chatIDarray[index];
    NSLog(@"%@", c.senderIDswift);
}
```

and this call the swift with jsqmessagesviewcontroller.
and then when i click a list from the table i get this error:

```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/C192F665-E5F4-4215-B858-115D64BFD8FC/FriendlyChatObjC.app> (loaded)' with name 'JSQMessagesViewController''
*** First throw call stack:
(0x18f0681c0 0x18daa055c 0x18f068108 0x1953b283c 0x10034eb34 0x100075670 0x100075bf8 0x194eb13dc 0x194ec8f70 0x1950514bc 0x194f69b84 0x194f697ec 0x194f69750 0x194eae54c 0x19237640c 0x19236b0e8 0x19236afa8 0x1922e7c64 0x19230f0d0 0x194ea3c1c 0x18f0157dc 0x18f01340c 0x18f01389c 0x18ef42048 0x1909c5198 0x194f1c628 0x194f17360 0x100073b20 0x18df245b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
```

I tried to follow any instruction from anywhere about this error and nothing fixed this.
Is there anything i miss?
Anyway I'm using the tutorial from raywenderlich for the swift part.

**Comment by Lucashuang0802** [comment] 2016-11-04 10:37
Hey, @ianstephens. Not really sure where the problem is based on the information you provided. I am just guessing around here. Perhaps `ChatViewController` is not inherited from `JSQMessagesViewController`? Or perhaps there is a mismatch with the *segue* setup? You can take a look at the sample we provide. It should lead you to a right direction.

**Comment by MacMeDan** [comment] 2016-11-18 23:49
Checkout the swift example from the development branch it will be your most update resource.

**Comment by RPasecky** [comment] 2017-01-19 06:40
Did you figure out what caused this? I'm having this problem after updating to cocoapods 0.39

**Comment by sathamkhussain** [comment] 2017-03-11 08:59
I'm facing same issue. Any solution?

**Comment by jessesquires** [comment] 2017-07-17 02:24
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:24 UTC
Labels: questions & help
