### ISSUE TITLE
textinput and keyboard space grows with every return or new line

### ISSUE THREAD

**Issue by Yoloabdo** [jessesquires/JSQMessagesViewController#2015] opened 2017-02-14 11:56 UTC
## New issue checklist

- [done ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.02
- Devices/Simulators: iPhone 7/6
- Reproducible in the demo project? (Yes/No):  no
- Any related issues:

## What happened?
input view just go above the keyboard with every new line 
![screen shot 2017-02-14 at 1 49 12 pm](https://cloud.githubusercontent.com/assets/1040866/22928099/4f41f6ee-f2bd-11e6-9e0f-8a2ff8e95cdf.png)

**Comment by hemantkadam** [comment] 2017-03-21 04:15
@Yoloabdo this looks bad but were you able to reproduce this issue in demo project? I'm using this lib since long but never faced such issue.
I'll need some more details on your implementation part.

**Comment by crazyfree** [comment] 2017-04-12 12:32
I had same problem, it caused by JSQMessagesComposerTextView:layoutSubviews you can temporary comment it out when waiting for owner answer

**Comment by crazyfree** [comment] 2017-04-13 01:28
@Yoloabdo i guess you also use IQKeyboardManagerSwift? if that, let remove it out. I got same problem and resolved it by removing IQKeyboardManagerSwift

**Comment by jessesquires** [comment] 2017-07-17 02:21
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:21 UTC
