### ISSUE TITLE
Multiple Warnings after pod update

### ISSUE THREAD

**Issue by argoel** [jessesquires/JSQMessagesViewController#1005] opened 2015-05-28 05:56 UTC
Hello

I am getting multiple warnings after installing the latest build of JSQMessageViewController. I just did pod update. Not sure how to address all of them. Attached are the warnings I am getting.

![screen shot 2015-05-27 at 10 56 23 pm](https://cloud.githubusercontent.com/assets/2237789/7853473/99a5f544-04c3-11e5-8d4e-034025221f44.png)

Any help would be really appreciated. Thanks!

**Comment by jessesquires** [comment] 2015-05-28 15:09
dupe of #828

this is fixed in the latest release.

**Closed by jessesquires** 2015-05-28 15:09 UTC

**Comment by argoel** [comment] 2015-05-28 19:40
Thanks. I updated my pods to the latest release. Was using the cocoapods stable before.. :)
