### ISSUE TITLE
Keyboard is presented over input bar during first access to view controller

### ISSUE THREAD

**Issue by yurybelevskiy** [jessesquires/JSQMessagesViewController#2132] opened 2017-06-18 18:23 UTC
## New issue checklist

- [Yes] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [Yes] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [Yes] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version: 7.3.4
- iOS version: 10.3.2
- Devices/Simulators: iPhone 7 Plus
- Reproducible in the demo project? (Yes/No): -
- Any related issues: https://github.com/jessesquires/JSQMessagesViewController/issues/2081

## What happened?
When first time opening chat controller, I auto-generate the welcome message as shown on the screenshot (keyboard goes over input bar):
![img_6499](https://user-images.githubusercontent.com/7622129/27263111-4b4c9c86-546c-11e7-9bd2-26840e5dd160.PNG)
If I pop controller from the stack and re-access it again, it always works. So, apparently, first load is always the problem.
I have `viewDidAppear()` defined like:
```
override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
  
        inputToolbar.contentView.textView.becomeFirstResponder()
}
```

I have already tried adding IQKeyboardManagerSwift to the project and that didn't help. Does anyone have an idea why is that happening?

**Comment by kjakm** [comment] 2017-06-19 09:01
I have the same issue however it's more intermittent. I initially thought it was related to rotation but I can't reproduce it frequently enough to debug.

**Comment by Lucashuang0802** [comment] 2017-06-26 00:38
@yurybelevskiy, thanks for submitting the issue. As for the issue, I was not able to replicate it in the demo project. Can you provide more info?

**Comment by gesabo** [comment] 2017-07-14 18:45
☝️  same issue

**Comment by gesabo** [comment] 2017-07-16 20:50
Has anyone else had this issue?  I feel like it's something I'm missing... again keyboard simply obscures the input bar so that you can't send a message

**Comment by jessesquires** [comment] 2017-07-17 01:59
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 01:59 UTC
