### ISSUE TITLE
Issue with avatar height and cell height

### ISSUE THREAD

**Issue by najdanovicivan** [jessesquires/JSQMessagesViewController#822] opened 2015-02-26 21:14 UTC
When JSQMessagesAvatarImage have greater height than JSQMessagesCollectionViewCell image is cropped to cell bounds. I have modified the JSQMessagesCollectionViewFlowLayout.m to make cell size always greater or equal to avatar image.

```objectivec

JSQMessagesCollectionViewFlowLayout.m

  - (CGSize)sizeForItemAtIndexPath:(NSIndexPath *)indexPath
 {
      CGSize messageBubbleSize = [self messageBubbleSizeForItemAtIndexPath:indexPath];
        JSQMessagesCollectionViewLayoutAttributes *attributes = (JSQMessagesCollectionViewLayoutAttributes *)[self layoutAttributesForItemAtIndexPath:indexPath];
    
    CGFloat finalHeight = messageBubbleSize.height;
    finalHeight += attributes.cellTopLabelHeight;
    finalHeight += attributes.messageBubbleTopLabelHeight;
    finalHeight += attributes.cellBottomLabelHeight;
    
    
    //FIXME: SIZE AVATAR
    
    //CGSize avatarSize = [self jsq_avatarSizeForIndexPath:indexPath];
    
    if (finalHeight < avatarSize.height)
        return CGSizeMake(self.itemWidth, avatarSize.height);
    
    return CGSizeMake(self.itemWidth, ceilf(finalHeight));
}
````

Now I have the different issue. The message bubble is also resized. It's ok with longer text, but on single line text messages the bubble have bigger bottom margin. Here are the screenshots

![ios simulator screen shot feb 26 2015 9 52 33 pm](https://cloud.githubusercontent.com/assets/6421209/6401882/e2fe3c8a-be03-11e4-97f8-542c57d5e038.png)
![ios simulator screen shot feb 26 2015 9 55 42 pm](https://cloud.githubusercontent.com/assets/6421209/6401883/e30fb906-be03-11e4-97e3-9bcf4c2fc457.png)

**Comment by jessesquires** [comment] 2015-02-27 01:03
duplicate of #564

**Closed by jessesquires** 2015-02-27 01:03 UTC
Labels: bug, duplicate
