### ISSUE TITLE
Constraints breaking at runtime when sending message

### ISSUE THREAD

**Issue by sasojadrovski** [jessesquires/JSQMessagesViewController#1007] opened 2015-06-01 11:27 UTC
I have noticed that the constraints are breaking at runtime after I press the send button and invoke the didPressSendButton:withMessageText:senderId:senderDisplayName:date method.

In this method I have only few lines of code among which:

```objective-c
[JSQSystemSoundPlayer jsq_playMessageSentSound];
// create the message...
[messages.allMessages addObject:newMessage];
[self finishSendingMessage];
```

Here is the console output of the exception:
```
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17029b080 V:[JSQMessagesLabel:0x135e86ce0(20)]>",
    "<NSLayoutConstraint:0x17029b170 V:[JSQMessagesLabel:0x135e86100(20)]>",
    "<NSLayoutConstraint:0x17029b6c0 V:[JSQMessagesCellTextView:0x136143e00]-(0)-|   (Names: '|':UIView:0x135e862d0 )>",
    "<NSLayoutConstraint:0x17029b760 V:|-(0)-[JSQMessagesCellTextView:0x136143e00]   (Names: '|':UIView:0x135e862d0 )>",
    "<NSLayoutConstraint:0x17029ba80 V:[JSQMessagesLabel:0x135e87780(0)]>",
    "<NSLayoutConstraint:0x17029bb70 V:|-(0)-[JSQMessagesLabel:0x135e86ce0]   (Names: '|':UIView:0x135e86bd0 )>",
    "<NSLayoutConstraint:0x17029bc60 V:[JSQMessagesLabel:0x135e86ce0]-(0)-[JSQMessagesLabel:0x135e86100]>",
    "<NSLayoutConstraint:0x17029bd00 V:[JSQMessagesLabel:0x135e86100]-(0)-[UIView:0x135e862d0]>",
    "<NSLayoutConstraint:0x17029be90 V:[JSQMessagesLabel:0x135e87780]-(0)-|   (Names: '|':UIView:0x135e86bd0 )>",
    "<NSLayoutConstraint:0x17029bee0 V:[UIView:0x135e862d0]-(0)-[JSQMessagesLabel:0x135e87780]>",
    "<NSAutoresizingMaskLayoutConstraint:0x17448fa00 h=--& v=--& V:[UIView:0x135e86bd0(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17029b6c0 V:[JSQMessagesCellTextView:0x136143e00]-(0)-|   (Names: '|':UIView:0x135e862d0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-06-01 13:19:48.278 Queet[25275:7087490] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x17029b080 V:[JSQMessagesLabel:0x135e86ce0(20)]>",
    "<NSLayoutConstraint:0x17029b170 V:[JSQMessagesLabel:0x135e86100(20)]>",
    "<NSLayoutConstraint:0x17029ba80 V:[JSQMessagesLabel:0x135e87780(0)]>",
    "<NSLayoutConstraint:0x17029bb70 V:|-(0)-[JSQMessagesLabel:0x135e86ce0]   (Names: '|':UIView:0x135e86bd0 )>",
    "<NSLayoutConstraint:0x17029bc60 V:[JSQMessagesLabel:0x135e86ce0]-(0)-[JSQMessagesLabel:0x135e86100]>",
    "<NSLayoutConstraint:0x17029bd00 V:[JSQMessagesLabel:0x135e86100]-(0)-[UIView:0x135e862d0]>",
    "<NSLayoutConstraint:0x17029be90 V:[JSQMessagesLabel:0x135e87780]-(0)-|   (Names: '|':UIView:0x135e86bd0 )>",
    "<NSLayoutConstraint:0x17029bee0 V:[UIView:0x135e862d0]-(0)-[JSQMessagesLabel:0x135e87780]>",
    "<NSAutoresizingMaskLayoutConstraint:0x17448fa00 h=--& v=--& V:[UIView:0x135e86bd0(38)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x17029b170 V:[JSQMessagesLabel:0x135e86100(20)]>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
```

Device, Xcode, JSQMessagesViewController and OS info:
* iPhone 5S, iOS 8.3
* Xcode Version 6.3.1
* JSQMessagesViewController version 7.0.2
* OS X Yosemite 10.10.3

Please take a look into this, or provide me with some instructions if something is wrong with my implementation. Thanks!

**Comment by jessesquires** [comment] 2015-06-01 15:14
thanks @sasojadrovski !

closing as a dupe of  #817

**Closed by jessesquires** 2015-06-01 15:14 UTC
Labels: bug, duplicate

**Comment by sasojadrovski** [comment] 2015-06-04 13:10
Hello @jessesquires 

I just want to add that when the constraints break at runtime, the typing indicator stops showing... The breaking of the constraints usually happens after exiting the Chat View Controller (it is in a Navigation VC, so it pops to root) and re-entering it. 

I hope you will find a solution to this one soon :)

All the best,
Sasho
