### ISSUE TITLE
InputToolbar appears in front of tabbar

### ISSUE THREAD

**Issue by srinathp90** [jessesquires/JSQMessagesViewController#1661] opened 2016-06-09 07:15 UTC
I've UITabBarController. This tabBar will appears behind the JSQMessagesInputToolbar. How can i make this JSQMessagesViewController smaller? am not using container view. This happens after updating to v7.3.2.I need to show InputToolbar above the tab bar. Please help me  i attached the screenshot. @jessesquires @mombrea 
![screen shot 2016-06-09 at 12 44 03 pm](https://cloud.githubusercontent.com/assets/9376405/15921565/ea87b1ea-2e3f-11e6-9fae-fccfed7af3c8.png)

**Comment by Sorix** [comment] 2016-07-18 09:02
I have the same issue on JSQMessagesViewController (from `https://github.com/jessesquires/JSQMessagesViewController.git`, branch `develop`).

**Comment by Lucashuang0802** [comment] 2016-07-25 07:25
@srinathp90 @Sorix Do you think you guys can replicate from the demo app? It's easier to debug 😄

**Comment by rurza** [comment] 2016-07-29 18:35
The same, but in my case it's behind toolbar.

<img width="1010" alt="screen shot 2016-07-29 at 20 34 46" src="https://cloud.githubusercontent.com/assets/2467137/17259480/f9a9d5d2-55cb-11e6-836c-a8d34124026a.png">

View hierarchy:
<img width="1135" alt="screen shot 2016-07-29 at 20 33 54" src="https://cloud.githubusercontent.com/assets/2467137/17259487/06173c6a-55cc-11e6-906d-c67e89bb1d64.png">

**Comment by Sorix** [comment] 2016-08-11 10:26
I’ve reproduced bug at demo project.

My steps:

1. Embedded Navigation Controller into Tab Bar.
2. Switched chat modal segue to push segue (no tabs will be in modal segue).
3. Added badges to Tab Bars, so you can see that chat is overlapping tabs incorrectly.

Demo project with bug reproduced: https://github.com/Sorix/JSQMessagesViewController/tree/tabbar-bug/SwiftExample

![bug](https://cloud.githubusercontent.com/assets/5610904/17585889/85450e10-5fcf-11e6-8c59-633f33e65ebb.png)

Also I think that bug more visible will be if we will modify tab bar height.

**Comment by cwalo** [comment] 2016-09-29 15:47
How about just hiding the TabBar when the MessagesViewController is pushed?
`messagesViewController.hidesBottomBarWhenPushed = true`

**Comment by Sorix** [comment] 2016-09-30 11:55
@cwalo, that is not correct solution, it's bad "hack" and somebody may need to show tab bar and chat simultaneously,

**Comment by cwalo** [comment] 2016-09-30 14:52
@Sorix I wouldn't necessarily call it a hack, but now that the expected/desired behavior is clearer, I can agree that it's not the solution.

**Comment by Prince009** [comment] 2016-10-01 02:39
@Sorix do u found any solution , i also suffer from this in my case, input toolbar hide on the tabbar... plz help me if you got any solution

**Comment by algrid** [comment] 2016-10-13 21:54
Currently inputToolbar is used as an inputAccessoryView for the ViewController. And it behaves the way it is. The only option I see to fix this is to not make it inputAccessoryView and control manually its position on keyboard show/hide. That's a bit of work, though.

**Comment by tapan-nathvani** [comment] 2017-01-19 10:12
is there any solution to show TabBar ?

**Comment by apwelsh** [comment] 2017-01-19 20:01
I use RDVTabBarController, and the older version of this tool (2.7?).  With this combo, it works.

**Comment by tapan-nathvani** [comment] 2017-01-20 04:24
As i am in the middle of the project, i cant change TabBar controller... Is there any solution in this tool to show TabBar with input toolbar ?

**Comment by MacMeDan** [comment] 2017-02-02 23:16
You can just make a content inset for the view to allow this. But it is a horrible idea because of the keyboard coming up. There is no way you should have a tabBar on a screen where the keyboard is shown IMO.

**Comment by jessesquires** [comment] 2017-07-17 02:22
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:22 UTC
Labels: bug, needs review

**Comment by Luten** [comment] 2018-06-01 11:45
Found a workaround by shifting toolbar frame by `bottomSpacing` = tabbar height:
```
- (void) layoutSubviews {
    [super layoutSubviews];
    CGRect origFrame = self.frame;
    origFrame.origin.y = _keyboardIsVisible ? 0 : -self.bottomSpacing;
    self.frame = origFrame;
}
```

Strangely it works well in JSQMessagesInputToolbar, but it's lost after animations if I do this in UIView that wraps toolbar, or maybe I'm missing something..
