### ISSUE TITLE
runtime error could not load NIB when using cocoapods 0.36

### ISSUE THREAD

**Issue by mypark** [jessesquires/JSQMessagesViewController#859] opened 2015-03-13 16:14 UTC
was working earlier but when I updated to the latest cocoapods and reinstalled the pods directory I get the following runtime error

NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle ... (loaded)' with name 'JSQMessagesViewController''

**Comment by jessesquires** [comment] 2015-03-13 17:57
Thanks @mypark - This is a dupe of #773.

I'm planning on pushing an update to CocoaPods very soon. Hopefully today or tomorrow.

**Closed by jessesquires** 2015-03-13 17:57 UTC
Labels: bug, duplicate, swift support
