### ISSUE TITLE
Some photos are vertically "crushed"

### ISSUE THREAD

**Issue by Zilounay** [jessesquires/JSQMessagesViewController#740] opened 2015-01-16 10:05 UTC
Hey Jesse,

I've updated JSQ to 6.1.3, and on iPhones 4S (ios 7 & 8) have some issues with media images.

Basically, i'm taking pictures with the `UIPickercameracontroller` (either from camera or from album library) and some pictures end up vertically compressed. But not all of them. I tried to find a pattern and I think : 
- It only happens with photo taken with the camera, and in portait orientation.

To note : my app does not rotate, and the pictures appear (for a very brief period of time) like they should, and then shrinks vertically to fit the cell.

Is it possible to "tell" the cell to simply crop the image vertically? or aspect fit it with black borders?

I tried : `cell.mediaView.contentMode = UIViewContentModeScaleAspectFit;`

But it doesn't seem to help

**Comment by betzerra** [comment] 2015-03-02 16:44
This is what's happening to me https://github.com/jessesquires/JSQMessagesViewController/issues/825

**Comment by BillCarsonFr** [comment] 2015-03-15 09:15
I have it to, only with portrait pictures.
It's strange if i do a long press on the bubble, there is a change and the  image  is not crush anymore (until the cell is refreshed, and  then it's back crush again)

**Comment by atfermin** [comment] 2015-04-07 02:25
Hey @jessesquires while my issue isn't exactly this, I think it's related. For my app I'm trying to implement stickers, but using JSQPhotoMediaItem crops the big ones.

![screen shot 2015-04-07 at 10 18 10 am](https://cloud.githubusercontent.com/assets/6512090/7016041/2decbaf2-dd10-11e4-8963-8fc15454abe5.png)

Is there a way to modify the frames to fit these stickers? I modified the content mode to aspect fit already.

**Comment by Zilounay** [comment] 2015-04-28 13:35
Yeah I can confirm that pressing the image makes it resize like it should.

If that is of any help, i'm often reloading the collectionview (every time there is a new message) ; is this how I should do it? I've tried using finishreceivingmessage or finishsendingmessage which doesn't matter, the photo still gets crushed pretty hard.

**Comment by Zilounay** [comment] 2015-05-22 12:04
Not to be annoying here, is there any news on this? I tried many different things and I couldn't get it to work properly. :(

My previous comment might help and makes me wonder ; how do you guys add messages to the view other than reloading it? maybe there is a JSQ method that I'm skipping (which would fix the problem).

My routine is just adding JSQMessages to the array and reloading the whole collectionview.

**Comment by DaniilForaSoft** [comment] 2015-06-09 06:46
[cell setHighlighted:YES];
[cell setSelected:YES];
in - (UICollectionViewCell *)collectionView:(JSQMessagesCollectionView *)collectionView cellForItemAtIndexPath:(NSIndexPath *)indexPath for media messages fix this for me

**Comment by borishart** [comment] 2015-11-17 00:53
I had this problem too and I was able to fix it by setting contentMode = UIViewContentModeScaleAspectFit and setting the .frame of imageView AFTER settings .contentMode, like so:

imageView.contentMode = UIViewContentModeScaleAspectFit;
imageView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);

**Comment by deptusto** [comment] 2016-01-07 16:53
Any news on the issue? I tried selecting and highlighting the cells, but that didn't work. For the fix proposed by @borishart, I am not quite sure where to put this code. I thought about increasing margins in the images, but this is far from neat and more like a temporary workaround.

**Comment by borishart** [comment] 2016-01-07 17:06
@deptusto This code is found in JSQMessagesViewController/Model/JSQPhotoMediaItem.m lines 83-84.

**Comment by deptusto** [comment] 2016-01-08 15:19
Unfortunately this didn't work, the images are still cropped :/

**Comment by anas-ambri** [comment] 2016-01-15 22:57
Can confirm that @borishart's solution worked for me. Any idea what is the reason for this?

In my case, I had this issue when long pressing on the images.

**Comment by Mkey85** [comment] 2016-03-01 20:08
@borishart thx worked

**Comment by happiehappie** [comment] 2016-04-01 11:16
Is there any way to dodge this at the moment without changing the source code?

**Comment by eliburke** [comment] 2016-04-01 12:52
Can anyone who has experienced this ( @happiehappie, @Mkey85, @anas-ambri, @deptusto, @borishart, etc) show this bug using the demo project, or if you are able to repeat it with a particular image, provide the image? I've not ever seen it myself

**Comment by happiehappie** [comment] 2016-04-01 15:01
<img width="432" alt="screen shot 2016-04-01 at 10 59 26 pm" src="https://cloud.githubusercontent.com/assets/6497131/14210855/847b54b4-f85d-11e5-9ded-948ce3c09b47.png">
example
http://beta.getfingers.com/files/gifts/12/PonmtgF28J.png
http://beta.getfingers.com/files/gifts/5/7CBbirLWzk.png
http://beta.getfingers.com/files/gifts/9/Ekm9e08PZV.png
http://beta.getfingers.com/files/gifts/12/PonmtgF28J.png

**Comment by happiehappie** [comment] 2016-04-01 15:02
Also, can anyone share how @atfermin center her photomedia?

**Comment by happiehappie** [comment] 2016-04-01 15:10
Demo project: 
<img width="432" alt="screen shot 2016-04-01 at 11 09 57 pm" src="https://cloud.githubusercontent.com/assets/6497131/14211122/eff4b5ae-f85e-11e5-96d4-0e15db44609b.png">

- (void)addPhotoMediaMessage
{   NSData *imageData = [NSData dataWithContentsOfURL:[NSURL URLWithString:@"http://beta.getfingers.com/files/gifts/12/PonmtgF28J.png"]];
    JSQPhotoMediaItem *photoItem = [[JSQPhotoMediaItem alloc] initWithImage:[UIImage imageWithData:imageData]];
    JSQMessage *photoMessage = [JSQMessage messageWithSenderId:kJSQDemoAvatarIdSquires
                                                   displayName:kJSQDemoAvatarDisplayNameSquires
                                                         media:photoItem];
    [self.messages addObject:photoMessage];
}

**Comment by eliburke** [comment] 2016-04-04 12:59
@happiehappie your images are being clipped because JSQPhotoMediaItem sets the imageView's contentMode to UIViewContentModeScaleAspectFill. Per Apple's docs, "Some portion of the content may be clipped to fill the view’s bounds."

If you don't want to modify the JSQMessages source code, I'd suggest a simple subclass of the PhotoMediaItem. Call it HappyPhotoMediaItem 😜, and in it you can sub in your own version of either 
`- (CGSize)mediaViewDisplaySize` (calculate the size you want) or
`- (UIView *)mediaView` (set the contentMode you want)

For example, here's a replacement for mediaViewDisplaySize that will adjust the image frame to portrait or landscape or square based on the image's native size.

```
- (CGSize)mediaViewDisplaySize {
    const CGFloat defaultSize = 128;
    CGSize thumbSize = CGSizeMake(defaultSize, defaultSize );
    if (self.image.size.height > 0 && self.image.size.width > 0) {
        CGFloat aspect = self.image.size.width / self.image.size.height;
        if (self.image.size.width > self.image.size.height) {
            thumbSize = CGSizeMake(defaultSize, defaultSize / aspect);
        } else {
            thumbSize = CGSizeMake(defaultSize * aspect, defaultSize);
        }
    }
    return thumbSize;
}
```

For a future release, it may be worthwhile to expose the contentMode as a property on JSQPhotoMediaItem, or update the way it calculates the image size. What do you think, @jessesquires ?

**Comment by jessesquires** [comment] 2016-04-04 14:38
>For a future release, it may be worthwhile to expose the contentMode as a property on JSQPhotoMediaItem

:+1: Sounds good to me!

**Comment by happiehappie** [comment] 2016-04-04 15:35
Sorry if this is answered elsewhere. But what about the centring >.<

On Monday, 4 April 2016, Jesse Squires <notifications@github.com> wrote:

> For a future release, it may be worthwhile to expose the contentMode as a
> property on JSQPhotoMediaItem
>
> [image: :+1:] Sounds good to me!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/jessesquires/JSQMessagesViewController/issues/740#issuecomment-205325931>
>


-- 
Best Regards,
Stanley

**Comment by eliburke** [comment] 2016-04-04 15:51
Check out #1521 I posted an answer and linked a fork with cell contents centered. You can combine this technique with a mediaItem subclass to fix your image size constraints.

**Comment by happiehappie** [comment] 2016-04-05 01:04
Ok. I'll try to "give back" when I'm done. I think I'll go with option 2.
Since my team doesn't commit pods. Hence hacking the code isn't a solution
for me. Thanks for being helpful everyone :)

**Comment by jessesquires** [comment] 2016-04-05 01:19
@happiehappie 

>Since my team doesn't commit pods.

I *used* to not commit pods as well. I would **strongly** encourage that you do. If you do, then *at any point in time* you can checkout, build, and run with no extra steps. Will be useful when you need to revert changes where changesets depend on different pod versions.

**Comment by happiehappie** [comment] 2016-04-05 02:02
Unfortunately my boss doesn't think so, I'll try to convince him down the road :( Off topic: This is my mock. Hehe. Btw thanks for the awesome library @jessesquires 
![chat](https://cloud.githubusercontent.com/assets/6497131/14269273/67ffc288-fb15-11e5-8864-b85a1427f139.png)

**Comment by jessesquires** [comment] 2016-04-05 04:24
Thanks @happiehappie ! :smile: Please keep reporting issues you find :blush:

**Comment by hammad** [comment] 2016-06-07 20:25
@borishart your solution worked for me too :)

**Comment by hermannkuschke** [comment] 2016-06-25 19:22
@borishart your solution worked for me as well! Much appreciated! @jessesquires I've never thanked you, but thanks for the very awesome component!

**Comment by Jeyhey** [comment] 2016-07-04 22:08
Still investigating after 1.5 years?

**Comment by eliburke** [comment] 2016-07-05 13:47
@Jeyhey the cause is known, and there are multiple solutions listed above. There will likely be a "standard" fix in the first 8.x release, but it won't be a one-size-fits-all perfect solution. Some people will want consistent bubbles, others will want full-frame images, etc.

**Comment by jessesquires** [comment] 2016-07-05 23:53
@Jeyhey 

> Still investigating after 1.5 years?

Yeah. Because this is free, open source code that no one gets paid to write. Anyone can submit a patch.

![](https://media.giphy.com/media/l46CsTPetihC1rX9K/giphy.gif)

**Comment by jessesquires** [comment] 2017-07-17 02:34
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:34 UTC
Labels: bug
