### ISSUE TITLE
Crash when inputting long text in input toolbar

### ISSUE THREAD

**Issue by sublimepremise** [jessesquires/JSQMessagesViewController#957] opened 2015-05-01 22:06 UTC
When the input toolbar's height increases to a certain level with a lot of characters (or line breaks), the app crashes when the message is sent.

An exception is raised at

    [self jsq_adjustInputToolbarForComposerTextViewContentSizeChange:dy]; 

I got the following error in the console:

    Unable to simultaneously satisfy constraints.
	    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 

    "<NSLayoutConstraint:0x17828e330 V:[JSQMessagesInputToolbar:0x154580c10(-1964)]>",
    "<NSLayoutConstraint:0x17828e920 V:[JSQMessagesToolbarContentView:0x1781fc700]-(0)-|        (Names: '|':JSQMessagesInputToolbar:0x154580c10 )>",
    "<NSLayoutConstraint:0x17828e880 JSQMessagesInputToolbar:0x154580c10.top ==     JSQMessagesToolbarContentView:0x1781fc700.top>"

    Will attempt to recover by breaking constraint 
    <NSLayoutConstraint:0x17828e880 JSQMessagesInputToolbar:0x154580c10.top ==     JSQMessagesToolbarContentView:0x1781fc700.top>

    Break on objc_exception_throw to catch this in the debugger.
    The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in     <UIKit/UIView.h> may also be helpful.

**Comment by sublimepremise** [comment] 2015-05-12 11:48
anyone else having a similar issue?

**Comment by jessesquires** [comment] 2015-05-12 15:30
duplicate of #469

**Closed by jessesquires** 2015-05-12 15:30 UTC
Labels: bug, duplicate
