### ISSUE TITLE
JSQAudioMediaItem -- multiple audio items playing simultaneously

### ISSUE THREAD

**Issue by jayjayesh** [jessesquires/JSQMessagesViewController#1786] opened 2016-08-08 10:32 UTC
when click on play button of one JSQAudioMediaItem bubble in chat screen and then click on play button of another JSQAudioMediaItem bubble , both audio file playing simultaneously.

How i can achieve only one audio file playing at a time.   

![simulatorscreenshot](https://cloud.githubusercontent.com/assets/10362928/17477701/4ff9bd8e-5d84-11e6-8d1c-acf9df65a5dd.png)

**Comment by Lucashuang0802** [comment] 2016-08-10 01:00
@jessesquires Looks like it's an bug if we don't allow to play simultaneously?

**Comment by GianniCarlo** [comment] 2016-08-10 02:08
@jayjayesh you need to specify another category for your AVAudioSession in your `JSQAudioMediaItem`'s property `audioViewAttributes.audioCategory`. You might want `AVAudioSessionCategorySoloAmbient`, here's the [Reference](AVAudioSessionCategorySoloAmbient) with the description

**Comment by GianniCarlo** [comment] 2016-08-10 02:17
@jessesquires or @Lucashuang0802 I have a question about `JSQAudioMediaItem` implementation, wouldn't it be better memory-wise to have just one `AVAudioPlayer` in the ViewController `JSQMessagesViewController` instead of having multiple players for each item? I would like to know what would be the downside of this approach? (I have something similar to this running on my project)

**Comment by eliburke** [comment] 2016-08-10 06:02
@giannicarlo yes that would be better. But it also creates a requirement for the implementer to create and maintain something orthogonal to the audio message feature. I erred on the side of simplicity.

I think a good enhancement would be to allow the audio media item to take an optional AVAudioPlayer item and use it if provided. That would allow implementers to roll their own singleton.

**Comment by Lucashuang0802** [comment] 2016-08-10 07:02
Hey @GianniCarlo, I agree with @eliburke. If the library provides a singleton object, developers will need to implement their own version of `AVAudioSession` for playing multiple audio files simultaneously if there are any use cases. Right now, they can simply implement a basic queue to play in turn.

**Comment by GianniCarlo** [comment] 2016-08-10 12:23
@eliburke thanks for the response, that certainly sounds like a great enhancement for the audio media item 👍

**Comment by jessesquires** [comment] 2016-08-16 05:58
Catching up on this thread.

1. Sounds like we should set `AVAudioSessionCategorySoloAmbient` ?
2. Let's definitely update `JSQAudioMediaItem` to (optionally) receive an `AVAudioPlayer`

**Comment by GianniCarlo** [comment] 2016-08-16 16:43
@jessesquires Point 1 might need to be investigated further, the current default `AVAudioSessionCategoryPlayback` normally doesn't allow mixing with other audio, and is better than `AVAudioSessionCategorySoloAmbient` given that the former doesn't care about the silent switch whereas the latter obeys it.

I think every chat out there ignores the silent switch when reproducing audio, that's why I'm mentioning it.

**Comment by GianniCarlo** [comment] 2016-08-16 16:49
Ok found out the problem, `onPlayButton:` in `JSQAudioMediaItem` is just setting the category:
```objective-c
[[AVAudioSession sharedInstance] setCategory:self.audioViewAttributes.audioCategory
                                         withOptions:self.audioViewAttributes.audioCategoryOptions
                                               error:&error];
```
besides that, you need to set active after that to enable it
```objective-c
[[AVAudioSession sharedInstance] setActive:YES error:&error];
```
This will notify the other audio playing and pause its sound

**Comment by GianniCarlo** [comment] 2016-08-16 18:19
OK, Upon further testing, looks like setting the category active only interrupts another app's audio. The thing is, AVAudioSession is a singleton, so if two of the demo player's set the audio session active, there is no notification given that the app's session was already active.

I'm stumped on how to make it work without a central piece which synchronizes the playback of the player. Any suggestions would be appreciated.

**Comment by eliburke** [comment] 2016-08-16 19:21
I hate working with AVAudio. The docs are entirely insufficient. I'm glad you kept testing this because I'd forgotten why I didn't have setActive anywhere in there. 

Another point of note: AVAudioSessionCategoryOptionDuckOthers only works if you are using Playback or PlayAndRecord. My users complained when their bluetooth music stopped, so I use that rather than Ambient or SoloAmbient. To me the fact that users can start multiple clips playing falls into the "well, don't do that" bin. 

A final thought, if we are determined to do more than just support a single AVAudioPlayer: there would be no provision for improved UI handling of multiple audio clips. Ideally if you are blocking playback of other clips, they should be disabled or have spinners over top. Or gain some indicator that they are queued. The whole point of the AudioMediaItem was to provide a usable base implementation, not a full on Voxer class push-to-talk app.

**Comment by GianniCarlo** [comment] 2016-08-17 23:32
Agreed, maybe the sinchronization of the playback is out of scope for this library. We should focus on Point 2 first at least: "update `JSQAudioMediaItem` to (optionally) receive an `AVAudioPlayer`"

**Comment by jessesquires** [comment] 2016-08-22 16:04
Sounds good to me. Thanks all for the input! 👍 

Let's definitely do (2) -- which will give clients the ability to solve this however they like. In the meantime, we can determine what's in/out of scope for the library. 😄

**Comment by jessesquires** [comment] 2017-07-17 02:23
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:23 UTC
Labels: feature request

**Comment by deore123** [comment] 2017-08-27 22:50
jayjayesh : Can you share the code for record and send audio files in chatView of JSQMessageView ChatController? I really appreciate your help
