### ISSUE TITLE
Can't scroll smoothly in CollectionView 

### ISSUE THREAD

**Issue by vedon** [jessesquires/JSQMessagesViewController#857] opened 2015-03-13 06:47 UTC
I use Iphone 5 to test the the demo you apply  ,the issue is ,with lots of text comments ,the collectionView can not scroll smoothly.

**Comment by BillCarsonFr** [comment] 2015-03-13 09:37
Hi Vedon,

If you are using iOS 8.x, it may be a duplicate of this issue:
https://github.com/jessesquires/JSQMessagesViewController/issues/492

I believe it's related to the new self sizing cell mechanism for collection views introduced in iOS8.
You can opt-out this mechanism by, adding this in JSQMessagesCollectionViewCell.m

    - (UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:    (UICollectionViewLayoutAttributes *)layoutAttributes
    {
        return layoutAttributes;
    }

Can you try this to see if you can now scroll smoothly? and if you notice side effects.
Thx.

**Comment by jessesquires** [comment] 2015-03-13 17:48
Thanks @BillCarsonFr and @vedon - this is a dupe of #492

**Closed by jessesquires** 2015-03-13 17:48 UTC
Labels: bug, duplicate

**Comment by ijinmao** [comment] 2015-03-14 14:17
@bitdeli-chef and @jessesquires I added preferredLayoutAttributesFittingAttributes in JSQMessagesCollectionViewCell.m, but the collection textView cell still can not scroll smoothly.

**Comment by jessesquires** [comment] 2015-03-14 18:19
@ijinmao - because `UITextView` is backed by TextKit as of iOS 7 and there were regressions in iOS 8.

**Comment by kartikthapar** [comment] 2015-03-14 18:22
Could this be useful in this case? https://github.com/jaredsinclair/JTSTextView

**Comment by jessesquires** [comment] 2015-03-14 18:54
thanks @kartikthapar ! :+1:

**Comment by ijinmao** [comment] 2015-03-15 03:36
@kartikthapar @jessesquires I changed the JSQMessagesCellTextView to JTSTextVIew, but I can still feel lags.
Would it be smoothly if I change JSQMessagesCellTextView from UITextView to TTTAttributedLabel?

**Comment by kartikthapar** [comment] 2015-03-15 03:53
There is an ongoing thread about scrolling performance on iOS. #492. Lets discuss there.

**Comment by vedon** [comment] 2015-03-17 08:17
@BillCarsonFr @jessesquires  thanks a lots ,I have test it for a long time .In the time profiler ,i find nothing to improve ...the preferredLayoutAttributesFittingAttributes ,I did't realized it .
