### ISSUE TITLE
Display Media (Picture) and Text on the same Bubble

### ISSUE THREAD

**Issue by felipericieri** [jessesquires/JSQMessagesViewController#764] opened 2015-01-28 13:29 UTC
Hi! First of all, thanks (too) for this amazing library!
I need to show text and media together (just like whatsApp do). I saw this is possible using JSQMessageMediaData protocol, but I need also resize my textView height to its content size and the method "mediaView" (which returns the UIView to display on UICollectionViewCell) is called after "mediaViewDisplaySize" (which returns its CGSize). So, after the UIView actually exists, I setted its width and height. How can I handle this?
Thank you again!

**Comment by jessesquires** [comment] 2015-01-28 17:15
Thanks @felipericieri !

Closing as duplicate of #681

**Closed by jessesquires** 2015-01-28 17:15 UTC
Labels: duplicate
