### ISSUE TITLE
Wrong message bubble width (iOS 10, iPad)

### ISSUE THREAD

**Issue by ChrisEdson** [jessesquires/JSQMessagesViewController#1844] opened 2016-09-27 09:33 UTC
## New issue checklist

- [x] I have read all of the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md). Confirmation: ____
- [x] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
### General information
- Library version(s): 7.3.4
- iOS version(s): 10.0
- Devices/Simulators affected: iPad Air / iPad Retina (possibly others)
- Reproducible in the demo project? (Yes/No): Yes
- Related issues: https://github.com/jessesquires/JSQMessagesViewController/issues/1212
### Expected behavior

Message cells are the correct width
### Actual behavior

Message cells are truncated
### Steps to reproduce

Build on XCode 8, iOS 10.0, iPad Retina or Air (not tested others). Does not occur on iOS 8 or 9.
### Crash log? Screenshots? Videos? Sample project?

Issue within my project:
![simulator screen shot 27 sep 2016 10 29 40](https://cloud.githubusercontent.com/assets/3041427/18867753/6193b348-849d-11e6-8a77-83d9a4565595.png)

Issue reproduced in demo project:
![simulator screen shot 27 sep 2016 10 30 43](https://cloud.githubusercontent.com/assets/3041427/18867793/87ebaf96-849d-11e6-80a5-e9d3302b3c30.png)

**Comment by codeOfRobin** [comment] 2016-10-05 14:48
I've got this error as well

**Comment by jasonn85** [comment] 2016-10-07 17:41
I was unable to reproduce this in the sample app, but I did have a very similar problem while using this inside of a split view.  I solved that problem by changing:

```- (void)viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator {
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
    [self jsq_resetLayoutAndCaches];
}```

to

```- (void) viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
        [super jsq_resetLayoutAndCaches];
    } completion:nil];
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
}```


I doubt that same change will fix this issue, but it may point in the right direction.

**Comment by ChrisEdson** [comment] 2016-10-07 18:16
Hey Jason - thanks, I'll give it a go. What Xcode version are you building on out of interest?

**Comment by algrid** [comment] 2016-10-08 21:19
I can reproduce this in the demo project. It looks like the wrong size is cached in JSQMessagesBubblesSizeCalculator. The problem is gone when I comment cached value usage:
```
- (CGSize)messageBubbleSizeForMessageData:(id<JSQMessageData>)messageData
                              atIndexPath:(NSIndexPath *)indexPath
                               withLayout:(JSQMessagesCollectionViewFlowLayout *)layout
{
//    NSValue *cachedSize = [self.cache objectForKey:@([messageData messageHash])];
//    if (cachedSize != nil) {
//        return [cachedSize CGSizeValue];
//    }

    CGSize finalSize = CGSizeZero;
...
```

**Comment by algrid** [comment] 2016-10-09 22:09
@ChrisEdson could you try this PR: https://github.com/jessesquires/JSQMessagesViewController/pull/1863

**Comment by ChrisEdson** [comment] 2016-10-10 12:07
Thanks @algrid, I'll give it a go!

**Comment by ChrisEdson** [comment] 2016-10-10 13:47
Tested - seems to be working on iOS 10 iPad. Great work!

**Comment by jessesquires** [comment] 2017-07-17 02:24
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:24 UTC
Labels: bug
