### ISSUE TITLE
[Springiness] Incorrectly sized message bubbles until I rotate - iPad and UITabBarController

### ISSUE THREAD

**Issue by sdnakhla** [jessesquires/JSQMessagesViewController#1122] opened 2015-07-27 18:15 UTC
I've implemented a messaging app on my iPad.  The messaging portion is inside of a UITabBarController, and is implemented as a UISplitViewController with the "Master" side a list of active conversations and the "Details" side the JSQMessagesViewController itself.  I find that when I select an item from the Master side and refresh the Details side, the message bubbles are incorrectly size.  They only end up 1-2 characters wide, and VERY tall.  (See the first screenshot)  After I rotate the device, however, the bubbles are resized and appear as expected.  (Second screen shot) When I select another conversation, however, they go back to being messed up.  Additionally, I get the following error messages...

    Please check the values return by the delegate.
    the behavior of the UICollectionViewFlowLayout is not defined because:
    the item width must be less than the width of the UICollectionView minus the section insets left and right values.

My assumption is that I'm not invalidating the layout or something properly.  Any idea what could be going on and how I could go about fixing it?
![ios simulator screen shot jul 27 2015 2 12 09 pm](https://cloud.githubusercontent.com/assets/4239452/8913921/f6c961cc-3469-11e5-88ba-4de8d2e3f4a4.png)
![ios simulator screen shot jul 27 2015 2 12 12 pm](https://cloud.githubusercontent.com/assets/4239452/8913922/f6cb40be-3469-11e5-95c9-5336ade64c1c.png)

**EDIT**  More info:  It seems that when I turn of the springiness of the collection view layout this problem resolves itself.  I don't know how this would cause a problem, but it definitely resolves the issue.

**Comment by sdnakhla** [comment] 2015-07-27 18:20
Also of concern is that the text entry bar at the bottom does not appear on the iPad when the JSQMessagesViewController is contained within a UITabBarController.  Thoughts on that?

**Comment by jessesquires** [comment] 2015-07-28 02:01
Thanks @sdnakhla

**Comment by olofd** [comment] 2015-09-13 16:29
I got this problem when using react native with JSQMessagesViewController and I set         messageViewController.view.frame = self.bounds; 
after I called 
 [self addSubview:messageViewController.view];

By changing the order. (First setting the frame) the issue went away.

**Comment by pirocso** [comment] 2015-09-18 15:36
I had the same issue but only on iOS 9. Commenting out these lines of code in JSQMessagesViewController fixed it for me. The collection view frame is not properly calculated in viewWillAppear so invalidating the layout there doesn't work:

- (void)viewWillAppear:(BOOL)animated
{
    NSParameterAssert(self.senderId != nil);
    NSParameterAssert(self.senderDisplayName != nil);
    
    [super viewWillAppear:animated];
//    [self.view layoutIfNeeded];
//    [self.collectionView.collectionViewLayout invalidateLayout];
    
    if (self.automaticallyScrollsToMostRecentMessage) {
        dispatch_async(dispatch_get_main_queue(), ^{
            [self scrollToBottomAnimated:NO];
            [self.collectionView.collectionViewLayout invalidateLayoutWithContext:[JSQMessagesCollectionViewFlowLayoutInvalidationContext context]];
        });
    }
    
    [self jsq_updateKeyboardTriggerPoint];
}

**Comment by yforjindam** [comment] 2015-11-11 18:33
I'm affected by this issue as well. The workaround suggested by @pirocso seems to fix the problem but presumably that code was in there for a reason. @jessesquires care to comment on what the right solution is here? That seems like a pretty core change to make even though it appears to fix the issue.

**Comment by jessesquires** [comment] 2015-11-11 19:22
Hey all -- I think #1238 fixes this properly. @harlanhaskins - can you confirm?

If so, looks like this issue is a dupe of #1212

**Comment by harlanhaskins** [comment] 2015-11-11 19:23
I really think it will fix it. Can you try your application with my PR?

**Comment by yforjindam** [comment] 2015-11-12 00:10
Jesse, Harlan,

The fix for #1238 fixes the problem I was seeing. It's funny though bc the
bubbles were sizing incorrectly on view load. As far as I can tell there
was no size class transition or anything like that so weird how this ended
up fixing it.

Jesse - is that the correct fix from a performance and maintainability
standpoint. I'm not at all familiar with those methods -
viewWillTransitionToSize:withTransitionCoordinator: but otherwise it seems
less scary than the other fix. Just don't want something else to break as a
result of this change - not knowing what caused the bug in the first place.

Thanks!

Cheers,

Yang Forjindam
Co-founder, PocketSuite
Voted* "best app for solopreneurs"
<http://www.forbes.com/sites/steveolenski/2015/01/27/3-top-apps-for-freelance-marketers-and-solopreneurs/>
*in
2015 by Forbes

**Comment by jessesquires** [comment] 2015-11-12 01:50
@yforjindam - Yes -- this would be the correct/proper fix.

The size class is likely transitioning because it the views are loaded from a `.xib` file.

**Comment by yforjindam** [comment] 2015-11-12 03:17
Thanks!

Cheers,

Yang Forjindam
Co-founder, PocketSuite
Voted* "best app for solopreneurs"
<http://www.forbes.com/sites/steveolenski/2015/01/27/3-top-apps-for-freelance-marketers-and-solopreneurs/>
*in
2015 by Forbes

**Comment by harlanhaskins** [comment] 2015-11-12 17:44
We should probably merge #1238 sooner rather than later...

**Comment by jessesquires** [comment] 2015-11-13 04:23
Based on discussion above, closing at dupe of #1212

**Closed by jessesquires** 2015-11-13 04:23 UTC
Labels: bug, duplicate
