### ISSUE TITLE
Get a building error after installed with cocoa pods

### ISSUE THREAD

**Issue by wangshengjia** [jessesquires/JSQMessagesViewController#1060] opened 2015-06-30 07:51 UTC
I have an issue when I try to install pod with Cocoapods v3.7.2, target on iOS8 and using use_frameworks!, but not the same as #927 

In my podfile:
**pod 'JSQMessagesViewController'**

I run the command "pod install" and get the output:
**Installing JSQMessagesViewController (7.1.0)**
**Installing JSQSystemSoundPlayer (2.0.1)**

Everything seems to be going well until I run the project, I get a build error:

**/Pods/JSQMessagesViewController/JSQMessagesViewController/Categories/JSQSystemSoundPlayer+JSQMessages.h:19:9: Include of non-modular header inside framework module 'JSQMessagesViewController.JSQSystemSoundPlayer_JSQMessages'**

Any ideas?

**Comment by jessesquires** [comment] 2016-03-11 17:06
Thanks @wangshengjia ! :smile: 

closing as duplicate of #1497

**Closed by jessesquires** 2016-03-11 17:06 UTC
Labels: bug, duplicate
