### ISSUE TITLE
Play button on JSQAudioMedia message does not work

### ISSUE THREAD

**Issue by kaiduanx** [jessesquires/JSQMessagesViewController#1705] opened 2016-07-04 15:14 UTC
Hi,

I got an issue to integrate JSQAudioMedia message in my project, the play button and length of the audio are both shown correctly, however the play button does not work. Clicking the play button does not play the audio.

The JSQMessagesViewController version is 7.3, and the device is iPhone 6s with iOS version 9.3.2.

Any idea where goes wrong and how to debug it?

Thanks,

/Kaiduan

**Comment by mwgray** [comment] 2016-07-06 18:22
Hi @kaiduanx,

I ended up having the same issue.  After lots of debugging I concluded that the JSQMessage I was supplying, as well as the JSQMessageMediaData was being released, which caused the view's callbacks to be released as well.  Once I made some strong references to the attachments, the button worked again.

Not sure if that is the intended behavior, but it works now.

**Comment by eliburke** [comment] 2016-07-06 18:55
@mwgray thanks for posting your experience. This is a good possibility to check. 

@kaiduanx if this suggestion doesn't help, start with a breakpoint in JSQAudioMediaItem's onPlayButton. Make sure the breakpoint triggers when the button is tapped. Make sure that self.audioPlayer and self.audioData are not nil *when the button is tapped*.

You can also check the mediaView method where the AVAudioPlayer is initialized to see if it is throwing an error, and implement the didChangeAudioCategory protocol to see if that is failing. It is possible that having an incompatible audio mode or category would cause problems.

**Comment by kaiduanx** [comment] 2016-07-06 19:28
@mwgray, and @eliburke thank you for sharing the thoughts and experience on this.

This is the way I supply JSQMessage,
    override func collectionView(collectionView: JSQMessagesCollectionView!,
                                 messageDataForItemAtIndexPath indexPath: NSIndexPath!) -> JSQMessageData! {
        let message = self.fetchController?.objectAtIndexPath(indexPath) as! MessageMO
        var JSQMsg:JSQMessage
            let audioData = getAudioData(message.sMessage!)
            let audio = JSQAudioMediaItem(data: audioData)
            audio.delegate = self
            JSQMsg = JSQMessage(senderId: message.sFrom!,
                                displayName: message.sFrom!,
                                media: audio)
        }
        return JSQMsg
    }

I set a breakpoint in the mediaView of JSQAudioMediaItem.m, the breakpoint was hit, and the audio data and audioPlayer were all set without problems.

However the breakpoint in onPlayButton was not hit when I click the play button.

I also set a delegate to the JSQAudioMediaItem, but the delegate function was not hit.
    // MARK: - JSQAudioMediaItemDelegate
    func audioMediaItem(audioMediaItem: JSQAudioMediaItem, didChangeAudioCategory category: String, options: AVAudioSessionCategoryOptions, error: NSError?) {
        DDLogInfo("audioMediaItem didChangeAudioCategory")
    }

BTW, my app is swift based.

**Comment by mwgray** [comment] 2016-07-06 19:34
@kaiduanx @eliburke 

That's pretty much what I had setup when I was seeing the issue.

From what I understand, the returned JSQMsg doesn't get stored anywhere by JSQMessagesViewController, and gets released.  Since the JSQMsg also owns the button & callbacks, those get released as well, resulting in the button not working.

**Comment by eliburke** [comment] 2016-07-06 19:49
I'm not sure what your self.fetchController is or might be, but if it is returning an object directly from your data source, you do not appear to be keeping a strong reference anywhere. You are constantly querying your data source, constructing objects, and then discarding them. This works for text because the JSQMessage's UILabel caches the text string. It works for JSQMPhotoMediaItem because there is a UIImage with a cached copy of decoded image bytes. It does not work for audio because the audio media item does not make a copy or keep a strong reference to the data. 

I think you can pretty easily test this theory by taking the result of your `let message = self.fetchController?.objectAtIndexPath(indexPath) as! MessageMO` and put it in an array you initialize in your JSQMessagesViewController class. Keep your code the same, add it to the array, and see if it fixes the problem-- long term you would need to do something like track the number of messages and pull them from the array and only call your fetchController if the message data is not available. Or if you don't want to keep the full chat data in an array, do like @kaiduanx and keep an array of attachments.

**Comment by kaiduanx** [comment] 2016-07-06 20:01
@eliburke, I save all the messages into core data. Thanks a lot for the detailed explanation, after storing all the AudioMediaItem and corresponding JSQMessage into a dictionary, the problem is gone.

**Comment by eliburke** [comment] 2016-07-06 20:46
🎉 👍 glad to hear it @kaiduanx

**Closed by eliburke** 2016-07-06 20:46 UTC
Labels: questions & help
