### ISSUE TITLE
I want to show toolbar above the tab bar so any solution for it?

### ISSUE THREAD

**Issue by RajeshJ89** [jessesquires/JSQMessagesViewController#1991] opened 2017-01-24 10:54 UTC
## New issue checklist

- [ ] I have read the [`README`](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/README.md), [documentation](http://cocoadocs.org/docsets/JSQMessagesViewController/), and [FAQ](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/Documentation/faq.md).
- [ ] [Contributing guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/.github/CONTRIBUTING.md) confirmation: ____
- [ ] I have searched [existing issues](https://github.com/jessesquires/JSQMessagesViewController/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.

## General information

- `JSQMessagesViewController` version:
- iOS version:
- Devices/Simulators:
- Reproducible in the demo project? (Yes/No): 
- Any related issues:

**Comment by acjh** [comment] 2017-01-24 11:14
Duplicate of #1661

**Closed** 2017-02-02 23:33 UTC
