### ISSUE TITLE
Unable to simultaneously satisfy constraints.

### ISSUE THREAD

**Issue by xbitlabs** [jessesquires/JSQMessagesViewController#1001] opened 2015-05-26 01:36 UTC
Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x182af780 V:[JSQMessagesLabel:0x182af5c0(20)]>",
    "<NSLayoutConstraint:0x182afea0 V:[JSQMessagesLabel:0x182afce0(20)]>",
    "<NSLayoutConstraint:0x182b3d80 V:[JSQMessagesCellTextView:0x15e35c00]-(0)-|   (Names: '|':UIView:0x182b0160 )>",
    "<NSLayoutConstraint:0x182b3de0 V:|-(0)-[JSQMessagesCellTextView:0x15e35c00]   (Names: '|':UIView:0x182b0160 )>",
    "<NSLayoutConstraint:0x182b43e0 V:[JSQMessagesLabel:0x182b42b0(0)]>",
    "<NSLayoutConstraint:0x182b4820 V:|-(0)-[JSQMessagesLabel:0x182af5c0]   (Names: '|':UIView:0x182af4e0 )>",
    "<NSLayoutConstraint:0x182b48b0 V:[JSQMessagesLabel:0x182af5c0]-(0)-[JSQMessagesLabel:0x182afce0]>",
    "<NSLayoutConstraint:0x182b4910 V:[JSQMessagesLabel:0x182afce0]-(0)-[UIView:0x182b0160]>",
    "<NSLayoutConstraint:0x182b4a00 V:[JSQMessagesLabel:0x182b42b0]-(0)-|   (Names: '|':UIView:0x182af4e0 )>",
    "<NSLayoutConstraint:0x182b4a30 V:[UIView:0x182b0160]-(0)-[JSQMessagesLabel:0x182b42b0]>",
    "<NSAutoresizingMaskLayoutConstraint:0x1824bb10 h=-&- v=-&- UIView:0x182af4e0.height == JSQMessagesCollectionViewCellIncoming:0x182af3d0.height>",
    "<NSLayoutConstraint:0x1824b560 'UIView-Encapsulated-Layout-Height' V:[JSQMessagesCollectionViewCellIncoming:0x182af3d0(39)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x182b3d80 V:[JSQMessagesCellTextView:0x15e35c00]-(0)-|   (Names: '|':UIView:0x182b0160 )>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
2015-05-26 09:31:30.495 Weishitong[1361:60b] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x182af780 V:[JSQMessagesLabel:0x182af5c0(20)]>",
    "<NSLayoutConstraint:0x182afea0 V:[JSQMessagesLabel:0x182afce0(20)]>",
    "<NSLayoutConstraint:0x182b43e0 V:[JSQMessagesLabel:0x182b42b0(0)]>",
    "<NSLayoutConstraint:0x182b4820 V:|-(0)-[JSQMessagesLabel:0x182af5c0]   (Names: '|':UIView:0x182af4e0 )>",
    "<NSLayoutConstraint:0x182b48b0 V:[JSQMessagesLabel:0x182af5c0]-(0)-[JSQMessagesLabel:0x182afce0]>",
    "<NSLayoutConstraint:0x182b4910 V:[JSQMessagesLabel:0x182afce0]-(0)-[UIView:0x182b0160]>",
    "<NSLayoutConstraint:0x182b4a00 V:[JSQMessagesLabel:0x182b42b0]-(0)-|   (Names: '|':UIView:0x182af4e0 )>",
    "<NSLayoutConstraint:0x182b4a30 V:[UIView:0x182b0160]-(0)-[JSQMessagesLabel:0x182b42b0]>",
    "<NSAutoresizingMaskLayoutConstraint:0x1824bb10 h=-&- v=-&- UIView:0x182af4e0.height == JSQMessagesCollectionViewCellIncoming:0x182af3d0.height>",
    "<NSLayoutConstraint:0x1824b560 'UIView-Encapsulated-Layout-Height' V:[JSQMessagesCollectionViewCellIncoming:0x182af3d0(39)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x182afea0 V:[JSQMessagesLabel:0x182afce0(20)]>

Break on objc_exception_throw to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.

**Comment by jessesquires** [comment] 2015-05-26 02:18
dupe of #817

**Closed by jessesquires** 2015-05-26 02:18 UTC
