### ISSUE TITLE
Leaky Linkification

### ISSUE THREAD

**Issue by bteitelb** [jessesquires/JSQMessagesViewController#761] opened 2015-01-24 00:22 UTC
On iOS 7.1, linkified URLs causes other messages to be linkified when they should not be.  

This is almost trivially reproducible in the demo included with JSQMessagesViewController:
  * Run the demo on an iOS 7.1 device (or the simulator)
  * Under “Demo Options / Settings”, enable “Load extra messages”
  * Select one of the presentation options
  * Send a message beginning with a URL (e.g. “http://vice.com”)
  * Scroll up and find that "Now with media messages!” is now linked to vice.com...

![ios simulator screen shot jan 23 2015 4 14 43 pm](https://cloud.githubusercontent.com/assets/24629/5885074/146218ea-a31b-11e4-8d65-d250aeadd859.png)

Perhaps a ```UITextView``` bug?  Perhaps a duplicate of #482?

**Comment by jessesquires** [comment] 2015-01-24 05:50
Thanks @bteitelb !

Closing as duplicate of #613

**Closed by jessesquires** 2015-01-24 05:50 UTC
