### ISSUE TITLE
Slight delay in scrolling to bottom when view first appears in iPhone 5S

### ISSUE THREAD

**Issue by riazhazan** [jessesquires/JSQMessagesViewController#1317] opened 2015-11-18 11:02 UTC
Slight delay in scrolling to bottom when view first appears in iPhone 5S. I m using the latest pod file. Do you have any idea why this issue is happening?

**Comment by jessesquires** [comment] 2015-11-18 17:09
Thanks @riazhazan !

Looks like this is a dupe of #1288. Going to close.

**Closed by jessesquires** 2015-11-18 17:09 UTC
Labels: bug, duplicate
