### ISSUE TITLE
Crahses on chat screen sometimes.

### ISSUE THREAD

**Issue by sathamkhussain** [jessesquires/JSQMessagesViewController#2039] opened 2017-03-13 10:31 UTC
My app using JSQMessages controller and it's crahses on chat screen with the following error.

*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: 'NSBundle </var/containers/Bundle/Application/5401514B-0B5E-4EA5-A395-680DD324F276/appname.app> (loaded)' with name 'niF-NV-pHi-view-mtR-K9-W16' and directory 'Main.storyboardc''

Initially app loads and running fine on the device with iOS 10.2, when I try to get into the chat screen for 3rd or 4th time, it crashing. And no crash with the simulator. 
When I search for "storyboardc" in my project, found the below,

 if [[ "$1" = /* ]] ; then
    RESOURCE_PATH="$1"
  else
    RESOURCE_PATH="${PODS_ROOT}/$1"
  fi
  if [[ ! -e "$RESOURCE_PATH" ]] ; then
    cat << EOM
error: **Resource "$RESOURCE_PATH" not found. Run 'pod install' to update the copy resources script.**
EOM
    exit 1
  fi
  case $RESOURCE_PATH in
    *.storyboard)
      echo "ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile ${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc $RESOURCE_PATH --sdk ${SDKROOT} ${TARGET_DEVICE_ARGS}"
      ibtool --reference-external-strings-file --errors --warnings --notices --minimum-deployment-target ${!DEPLOYMENT_TARGET_SETTING_NAME} --output-format human-readable-text --compile "${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/`basename \"$RESOURCE_PATH\" .storyboard`.storyboardc" "$RESOURCE_PATH" --sdk "${SDKROOT}" ${TARGET_DEVICE_ARGS}

  Please help to fix this issue.

**Comment by apwelsh** [comment] 2017-03-13 16:33
This is a shell script, and has nothing to do with a runtime crash.  Usually a full stack trace dump is helpful in isolating the root cause. Somwtime the error reported is a side effect of a previous call. If you are using a variable to reference a custom nib (for instance) and the reference is a weak reference, it is possible the handle is pointing to garbage at time of use. (Not that this is the case)

**Comment by sathamkhussain** [comment] 2017-03-14 05:18
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001088bed4b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010b4f221e objc_exception_throw + 48
	2   CoreFoundation                      0x00000001089282b5 +[NSException raise:format:] + 197
	3   UIKit                               0x000000010962abd2 -[UINib instantiateWithOwner:options:] + 507
	4   UIKit                               0x00000001093be9c5 -[UIViewController _loadViewFromNibNamed:bundle:] + 386
	5   UIKit                               0x00000001093bf2e7 -[UIViewController loadView] + 177
	6   UIKit                               0x00000001093bf61c -[UIViewController loadViewIfRequired] + 201
	7   UIKit                               0x00000001093c6062 -[UIViewController __viewWillAppear:] + 118
	8   UIKit                               0x00000001093f11d3 -[UINavigationController _startCustomTransition:] + 1290
	9   UIKit                               0x0000000109401e48 -[UINavigationController _startDeferredTransitionIfNeeded:] + 697
	10  UIKit                               0x0000000109402fdb -[UINavigationController __viewWillLayoutSubviews] + 58
	11  UIKit                               0x00000001095f9dd7 -[UILayoutContainerView layoutSubviews] + 223
	12  UIKit                               0x00000001092e2ab8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1237
	13  QuartzCore                          0x000000010ab61bf8 -[CALayer layoutSublayers] + 146
	14  QuartzCore                          0x000000010ab55440 _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 366
	15  QuartzCore                          0x000000010ab552be _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 24
	16  QuartzCore                          0x000000010aae3318 _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 280
	17  QuartzCore                          0x000000010ab103ff _ZN2CA11Transaction6commitEv + 475
	18  UIKit                               0x0000000109216d9b _UIApplicationFlushRunLoopCATransactionIfTooLate + 206
	19  UIKit                               0x0000000109a2177c __handleEventQueue + 5672
	20  CoreFoundation                      0x0000000108863761 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	21  CoreFoundation                      0x000000010884898c __CFRunLoopDoSources0 + 556
	22  CoreFoundation                      0x0000000108847e76 __CFRunLoopRun + 918
	23  CoreFoundation                      0x0000000108847884 CFRunLoopRunSpecific + 420
	24  GraphicsServices                    0x000000010d505a6f GSEventRunModal + 161
	25  UIKit                               0x000000010921dc68 UIApplicationMain + 159
	26  IT HELPDESk                         0x00000001081b5aa2 main + 114
	27  libdyld.dylib                       0x000000010d66368d start + 1
	28  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by jessesquires** [comment] 2017-07-17 02:15
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:15 UTC
