### ISSUE TITLE
Custom font issue

### ISSUE THREAD

**Issue by Katafalkas** [jessesquires/JSQMessagesViewController#904] opened 2015-04-01 16:02 UTC
I noticed there where few issues with custom fonts which were fixed, and not sure if this is another one of I am just doing something wrong.
using `pod 'JSQMessagesViewController', '~> 7.0'` and `Swift 1.2`

This is with default font:

![defaultfont](https://cloud.githubusercontent.com/assets/1636440/6945245/01a0bf20-d8a1-11e4-8eec-209812e1e5c4.png)

And this is after I add font to `self.collectionView.collectionViewLayout.messageBubbleFont`:

![customfont](https://cloud.githubusercontent.com/assets/1636440/6945269/32d9ad90-d8a1-11e4-8e06-34af6bd7a5f4.png)

Am I missing something ?
Also - maybe there is some way to send your own `CGSize` value for bubble size and textView for each cell at indexPath ?

**Comment by jessesquires** [comment] 2015-04-01 16:31
duplicate of #347

**Closed by jessesquires** 2015-04-01 16:31 UTC
