### ISSUE TITLE
Lost text of last message after use the lens.

### ISSUE THREAD

**Issue by OrWest** [jessesquires/JSQMessagesViewController#1423] opened 2016-02-01 08:35 UTC
Lost text of last message after use the lens (long tap on textView in inputToolBar) in chat. Bug with small messages (text).
It's demo project, downloaded from repo 01.02.

**Lib version: 7.2.0
iOS version: 9.2.1
Device: iPhone 5**

![img_0133](https://cloud.githubusercontent.com/assets/12881398/12712135/0a748542-c8d7-11e5-8d76-af2a3682cfa0.PNG)
![img_0134](https://cloud.githubusercontent.com/assets/12881398/12712136/0aa0811a-c8d7-11e5-8bdb-e7178f5119d9.PNG)

**Comment by OrWest** [comment] 2016-03-15 09:33
Any ideas? I can provide movie with this bug, if you want.

**Comment by Kayoto1** [comment] 2016-03-15 11:45
Same happen to me

**Comment by OrWest** [comment] 2016-05-23 07:40
Any moving?

**Comment by Lucashuang0802** [comment] 2016-07-25 07:16
@OrWest Can you provide more info? I can't replicate the issue. Thx! 😄

**Comment by jessesquires** [comment] 2016-07-25 15:59
@OrWest - I'm going to close this for now since we can reproduce it.

If you have anymore information, please update here and we can re-open. If you can setup steps to reproduce in our demo project, that would be most helpful. Thanks! 😄

**Closed by jessesquires** 2016-07-25 15:59 UTC
Labels: questions & help

**Comment by OrWest** [comment] 2016-08-09 08:52
I think this bug relates to textField. So in actual iOS version this bug doesn't reproducible already.
