### ISSUE TITLE
Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'

### ISSUE THREAD

**Issue by datomnurdin** [jessesquires/JSQMessagesViewController#960] opened 2015-05-05 13:03 UTC
I got this warning message after updated latest pod.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/JSQMessagesViewController/JSQMessagesViewController/Layout/JSQMessagesCollectionViewFlowLayout.h:59:60: Property type 'JSQMessagesCollectionView *' is incompatible with type 'UICollectionView *' inherited from 'UICollectionViewLayout'
```

Code

```
@property (readonly, nonatomic) JSQMessagesCollectionView *collectionView;
```

Please advice. Thank you.

**Comment by jessesquires** [comment] 2015-05-05 14:58
fixed in 7.0.1. duplicate of #920

**Comment by jessesquires** [comment] 2015-05-05 14:58
please don't open duplicate issues.

**Closed by jessesquires** 2015-05-05 14:58 UTC
