### ISSUE TITLE
Auto-layout constraint warnings (re-open of #322)

### ISSUE THREAD

**Issue by federicocappelli** [jessesquires/JSQMessagesViewController#817] opened 2015-02-24 18:09 UTC
Hi guys, this happens in version 6.1.3, iOS 8.1.2, storyboard+size classes sometimes when the view render messages

```
2015-02-24 16:34:52.289 xxx[9544:274546] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x7f885acd7550 V:[JSQMessagesLabel:0x7f885acd7200'Today 4:29 PM'(20)]>",
    "<NSLayoutConstraint:0x7f885acdc420 V:[JSQMessagesLabel:0x7f885acdc0d0'Tony Parker has invited F...'(20)]>",
    "<NSLayoutConstraint:0x7f885acf9fc0 V:|-(0)-[JSQMessagesLabel:0x7f885acd7200'Today 4:29 PM']   (Names: '|':UIView:0x7f885acd7130 )>",
    "<NSLayoutConstraint:0x7f885acfa0b0 V:[JSQMessagesLabel:0x7f885acd7200'Today 4:29 PM']-(0)-[JSQMessagesLabel:0x7f885acdc0d0'Tony Parker has invited F...']>",
    "<NSLayoutConstraint:0x7f885acfa150 V:[JSQMessagesLabel:0x7f885acdc0d0'Tony Parker has invited F...']-(0)-[UIView:0x7f885acdcab0]>",
    "<NSLayoutConstraint:0x7f885acfa1f0 V:[UIView:0x7f885acdcab0]-(0)-[JSQMessagesLabel:0x7f885acf96c0]>",
    "<NSLayoutConstraint:0x7f885acfa290 V:[JSQMessagesLabel:0x7f885acf96c0]-(0)-|   (Names: '|':UIView:0x7f885acd7130 )>",
    "<NSAutoresizingMaskLayoutConstraint:0x7f885afe5f20 h=--& v=--& V:[UIView:0x7f885acd7130(20)]>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x7f885acdc420 V:[JSQMessagesLabel:0x7f885acdc0d0'Tony Parker has invited F...'(20)]>
```

**Comment by jessesquires** [comment] 2015-02-27 02:11
hey @federicocappelli - size classes are not fully support as this library is iOS 7+

**Comment by federicocappelli** [comment] 2015-02-27 09:37
ok thanks @jessesquires any plans for future releases?

**Comment by jessesquires** [comment] 2015-02-27 19:59
@federicocappelli - definitely. #499

**Comment by jessesquires** [comment] 2015-03-22 23:40
Marking this as a duplicate of #322 and continue tracking that issue here.

**Comment by harlanhaskins** [comment] 2015-03-22 23:42
For record-keeping purposes, I'm not using size classes, and my subclass of `JSQMessagesViewController` doesn't touch a Storyboard.

**Comment by jessesquires** [comment] 2015-03-22 23:43
@harlanhaskins - can you provide steps or show how to repro with the demo project?

**Comment by harlanhaskins** [comment] 2015-03-23 18:31
@jessesquires I'll pull out our messaging code into a small demo and post it here with some dummy data.

**Comment by harlanhaskins** [comment] 2015-04-01 16:40
I've tried a bit to pull my messaging code out, but it's complex and unfortunately fairly coupled to the rest of my implementation.

I see the Auto Layout issues usually when adding messages, 

```swift
func messageGroup(group: MessageGroup, didAddMessages messages: [Message]) {
    // Build a list of valid index paths from the messages provided, by throwing out
    // messages that don't exist in the list.
    let paths: [NSIndexPath] = mapMaybe(messages) { message in
        if let index = find(group.messages, message) {
            return NSIndexPath(forItem: index, inSection: 0)
        }
        return nil
    }
    self.collectionView?.performBatchUpdates({
        self.collectionView?.insertItemsAtIndexPaths(paths)
        return
    }, completion: { finished in
        self.finishReceivingMessages()
   })
}
```

**Comment by jardamach** [comment] 2015-06-15 21:01
@jessesquires Hi Jesse, I may have found cause of the constraint troubles... it seems that placing this (little bit ugly and hacky) line

    [self.contentView setBounds:CGRectMake(0, 0, CGRectGetWidth(self.contentView.frame), 15000)];

15000 - some big number ==> temporary cell height

right above 
    [self jsq_updateConstraint:self.messageBubbleContainerWidthConstraint
                  withConstant:customAttributes.messageBubbleContainerViewWidth];

inside method:
    - (void)applyLayoutAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes 

fixes constraints conflicts (at least in our app). Apparently constraint conflict pops up when you update cell with new for example customAttributes.cellTopLabelHeight and the sum of current updated constraint constants is bigger than incoming dequeued cells bounds.height which makes constraint gods confused. 

Setting bounds.height to some big number takes care of the problem because there is a lot of space during constraint updates. Then, bounds are properly updated during collection view cell update process.

There might be some more elegant solution but this seems to work. ;-)

(this comment gave me a hint: https://github.com/Alex311/TableCellWithAutoLayout/commit/bde387b27e33605eeac3465475d2f2ff9775f163#commitcomment-4633188)

**Comment by harlanhaskins** [comment] 2015-06-16 17:57
It looks like it's related to `NSAutoresizingMaskLayoutConstraint`s. It doesn't look like `[self.contentView setTranslatesAutoresizingMasksIntoConstraints:NO];` is happening anywhere.

**Comment by stefanocdn** [comment] 2015-06-17 22:28
@harlanhaskins I am experiencing this autolayout issue when scrolling quicky, and noticed you mentionned that occured also to you when scrolling in another thread. Have you found a solution for the scrolling error? I am not using storyboard or xib.

**Comment by harlanhaskins** [comment] 2015-06-17 22:58
It definitely happens when I scroll quickly. When I do a load earlier messages call and I get about 30 messages, `self.collectionView.reloadData()` causes all these warnings. So it's gotta be related to rapid cell insertion.

**Comment by jardamach** [comment] 2015-06-18 07:59
@stefanocdn @harlanhaskins: Hi, have you tried the trick with bounds height mentioned above?

**Comment by JRam13** [comment] 2015-07-05 18:47
@jardamach I can confirm that this helped with the constraint warnings. I was seeing them for the same reason @harlanhaskins was (rapid cell insertions/scrollToBottom). 

Nice fix, thanks.

**Comment by hwaxxer** [comment] 2015-10-16 19:36
Thanks @jardamach for the fix. Worked for me.

**Comment by hwaxxer** [comment] 2015-10-20 17:45
I take that back. Reloading items now leads to weird flickering.

**Comment by Luke47** [comment] 2015-12-01 15:36
Did you guys managed to fix this? Getting layout constraints warnings, when I have different heights of top labels for individual cells. No warnings, if they are all the same.

**Comment by wongyt2008** [comment] 2016-03-20 08:22
@jardamach  Your solution works for me. Thank you for that.

**Comment by eliburke** [comment] 2016-04-26 17:03
I just triggered this problem inadvertently and it took me a good couple hours to figure out the cause. While debugging an autolayout bug, I mistakenly turned off autoresizing in the navigation controller: 
`self.navigationController.view.translatesAutoresizingMaskIntoConstraints = NO;`
Setting translatesAutoresizingMaskIntoConstraints = NO in the JSQMessagesViewController class prevents the NSLayoutConstraints exception, but wrecks the app by helpfully re-sizing everything in the view hierarchy to a width of 0. 

I can reproduce the problem in the demo project by adding the same line to TableViewController:viewDidLoad. Of all the views in my app, this only happens with JSQMessagesViewController but I don't know if it is a bug, or just a "don't do that". 

Anyhow, if anyone else has this bug, I hope this info helps.

**Comment by jessesquires** [comment] 2016-04-29 15:57
> this only happens with JSQMessagesViewController but I don't know if it is a bug, or just a "don't do that".

ha, i think this is "just don't do that" 😄 we *want* `translatesAutoresizingMaskIntoConstraints = YES` in this case.

**Comment by bitomule** [comment] 2016-06-14 18:52
I have a similar issue when I return different heights in labels height methods.

**Comment by bitomule** [comment] 2016-06-23 16:40
@jardamach trick worked. Do I have to create a fork to use it or there's a "real" plan to fix this issue without hacks? I can create the PR with the hack but not sure if resetting bounds before setting constraints could break any other thing or cause performance problems.

**Comment by bitomule** [comment] 2016-06-24 11:50
@jardamach found an issue with this approach, when I add a new cell and call finishSending method and it triggers collectionView.reloadData and layout goes crazy

**Comment by bitomule** [comment] 2016-06-24 12:15
Changing code on finishSending to avoid reloadData and insert row instead fixes the issue. I've also added a check to avoid the hack when expected layout is smaller than current (when this hack is not needed)

**Comment by jessesquires** [comment] 2017-07-17 02:35
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:35 UTC
Labels: bug, duplicate, hard, priority: high
