### ISSUE TITLE
Custom Font: message is not displayed completely when using custom font, or non-default font size

### ISSUE THREAD

**Issue by harshitaahuja** [jessesquires/JSQMessagesViewController#347] opened 2014-06-09 09:23 UTC
I added below code in viewdidload method in JSQDemoViewController.m .It shows starange behavior with message having even number of lines shown in screenshot.

```
self.collectionView.collectionViewLayout.messageBubbleFont = [UIFont fontWithName:@"HelveticaNeue-Light" size:17.0f];
```

![ios simulator screen shot 09-jun-2014 2 49 02 pm](https://cloud.githubusercontent.com/assets/3863417/3214868/4bcabe4e-efb7-11e3-9159-7c8e820c2c9d.png)

**Comment by realsurfer** [comment] 2015-01-23 18:11
FYI, just updated to the latest 6.1.3 build and this issue was still there.

**Comment by markrickert** [comment] 2015-02-05 02:34
Just chiming in here. I'm having a problem using Gotham-Book 14. There's a bunch of extra space under the message text, and some text gets cut off (notice the website is missing from the 3rd cell on the last line)

![ios simulator screen shot feb 4 2015 9 33 06 pm](https://cloud.githubusercontent.com/assets/139261/6054010/9646f904-acb5-11e4-9309-d149c36603c6.png)

**Comment by fer662** [comment] 2015-03-19 15:26
+1 to piercifani's solution

**Comment by dmitruss** [comment] 2015-04-16 13:54
+1

**Comment by nexon** [comment] 2015-07-08 11:30
Any news about this issue?.

**Comment by jessesquires** [comment] 2015-07-08 14:41
I do have a solution for v7.1.2.

Unfortunately, my time is limited for this project at the moment.

**Comment by nexon** [comment] 2015-07-08 16:04
Cool, no problem.

**Comment by fpena** [comment] 2015-07-30 21:02
@jessesquires is there a way you could explain your solution a bit, so everyone can try tackle it? 

Thanks!

**Comment by jessesquires** [comment] 2015-08-13 04:39
Hello all! Finally closing this issue as fixed! :tada:

But don't get too excited yet. When I say "fixed", I don't mean that I fixed it. I mean that I've given you a brand new opportunity to fix it yourself! :smile: You're welcome! :smile:

OK. Joking aside, bubble sizes can be so tricky to calculate for all of the different fonts and there are tons of edge-cases, etc. Because of this, I've implemented an easy-to-use hook where you can calculate sizes for your own custom fonts!

#### New on `JSQMessagesCollectionViewFlowLayout`:

````objective-c
@property (strong, nonatomic) id<JSQMessagesBubbleSizeCalculating> bubbleSizeCalculator;
````

The default value for this is a `JSQMessagesBubblesSizeCalculator` instance. This maintains current behavior.

Checkout the header docs and the commit above (983fb58) for more details. 

This will be in the next release. Sync with `develop` to get it now.

**Closed by jessesquires** 2015-08-13 04:39 UTC
Labels: bug, feature request

**Comment by promisenxu** [comment] 2015-08-31 05:30
I have been tackling this problem for some time now and I actually notice two potential problems with how the size of the bubble is calculating.

1 - When calculating the finalWidth, the spacingBetweenAvatarAndBubble should be deducted from stringSize.width + horizontalInsetsTotal. spacingBetweenAvatarAndBubble was included in horizontalInsetsTotal but it's obviously not part of the message bubble size.

2 - This one builds on our team's speculation regarding boudingRectWithSize.

It's known that the width returned by the function could be larger or smaller than the maximumTestWidth we provided. However, in the instance that it's multiple lines of text and the width returned is actually larger than the maximumWidth, if we use the actual returned width, we run into problem of sometimes having an extra line at the bottom.

The calculation of string size takes into consideration many things - corner cases are those lines ending with punctuations and lines with mixed languages. In short, there are cases that even though the returned width is (slightly) larger than the maximumWidth, a text view's container view will only need the maximumWidth to display itself - if we supply it with the actual return width, the text container view may now be able to fit in one more character at the end of a line and leave us with an extra line.

We circumvent this by also calculating the height of the text when all put into one line (e.g. boundingRectWithSize with CGFloatMax passed into width and height). If the returned height from the boundingRectWithSize with maximumWidth and CGFloatMax as height is larger than the one-line height, we pass the maximumWidth instead.

This will leave some empty space at the far side of the bubble.

----------------------------------

With these two fixes, my bubble size are all correct and I don't need the extra 2 magic px on the width. But I still need the extra 2 px on the height. Sigh still couldn't solve that one.

Hope these help.

**Comment by jessesquires** [comment] 2015-09-01 04:55
Thanks @promisenxu !

Please consider submitting a PR if you think it will help the library.

**Comment by promisenxu** [comment] 2015-09-01 05:00
Sure thing! Very new to iOS programming and GitHub - will learn how to submit a PR shortly.

Appreciations to you @jessesquires . It's a wonderful project you have spearheaded and built and it certainly saved us countless hours of work.

**Comment by rosslebeau** [comment] 2015-09-02 16:19
@jessesquires @promisenxu 

I believe I have found a solution. Basically, the bounding box that `boundingRectWithSize:...` gives you is allowed to be larger than the size you pass in (from the [docs](https://developer.apple.com/library/ios/documentation/UIKit/Reference/NSString_UIKit_Additions/index.html#//apple_ref/occ/instm/NSString/boundingRectWithSize:options:attributes:context:)). I guess this is due to text drawing being weird. So, say we give it a bounding width of 200, the method is allowed to return something like 204. The current bubble size calculator will then take that 204 and use it as the text width. However, we just told `boundingRectWithSize:...` that we would bound the text to 200! So when we make the actual text container bounds to be 204 now, sometimes there is enough room to move all the text from what was the final line up into other lines.

Anyway, my solution is [here](https://github.com/rosslebeau/JSQMessagesViewController/commit/416594b822749a84f42e3dee668e5f00a5a4bd41) and it's pretty simple. It works with all the different sizes and stuff I've tried in my app (including emoji) that were broken before, and I would love if you guys could test it out with your apps and let me know if there are still issues. I'm happy to make a PR if you are satisfied that this is a solution, or at least an improvement.

**Comment by promisenxu** [comment] 2015-09-02 17:56
@jessesquires @rosslebeau 

Yes that's what I did as well. One difference is that I switch to maximumWidth when there are multiple line of text. Your method definitely looks better, however I'm not sure if there are cases when the returned width is slightly smaller than maximumWidth and would require us to switch to maximumWidth.

I was very surprised to see in your code that you don't need the 2px magix for the final height - that's the last bit unsolved in my implementation. Simply removing it and my text will not show the last line if there are multiple lines.

What font did you test with? I have been using
_messageBubbleFont = [UIFont preferredFontForTextStyle:UIFontTextStyleBody];

When I switched to _messageBubbleFont = [UIFont systemFontOfSize:17.0f]; (any size), I don't need the 2px either! Is the preferredFontForTextStyle doing something weird?

**Comment by promisenxu** [comment] 2015-09-02 18:09
@jessesquires @rosslebeau 

Forgot to mention yes I think you should totally create a PR for this. Working beautifully for me now.

**Comment by rosslebeau** [comment] 2015-09-02 19:53
@promisenxu 

Very interesting, I see that it does in fact cut off the final line, but only when using `preferredFontForTextStyle`, which also happens to be the default for this library. I was using a custom font.

The really interesting part is that when I look at the `preferredFontForTextStyle` on my device, it is exactly the same as `systemFontOfSize:17.0` except for the fontDescriptor has `NSCTFontUIUsageAttribute = UICTFontTextStyleBody;` instead of `NSCTFontUIUsageAttribute = CTFontRegularUsage;`. The font name, size, and symbolicTraits are the same, as are the other font properties like ascender, leading, etc.

The 2px magic is also needed with other "preferredFont" styles. The `boundingRectWithSize:...` method appears to just be broken for these...

I looked into this a bunch, but I have to move on for today. I'll spend some more time later, but at this point I don't know how much more information I can find out about `NSCTFontUIUsageAttribute` and the internals of `boundingRectWithSize:...` without talking to someone from Apple.

**Comment by jessesquires** [comment] 2015-09-03 06:36
Thanks so much @promisenxu and @rosslebeau ! :tada: 

Lots of interesting information there.

>The `boundingRectWithSize:...` method appears to just be broken for these...
@rosslebeau - Please file a radar :smile: 

Would love to see a PR :smile:

**Comment by rosslebeau** [comment] 2015-09-03 14:03
@jessesquires I think I have an approach that works for both using CoreText, but I need to do more research and make sure performance is acceptable. I should be able to have a PR sometime this weekend that won't under- or over-shoot lines, even if I'm just switching on the `NSCTFontUIUsageAttribute`.

**Comment by rosslebeau** [comment] 2015-10-25 18:04
Ok update on this:

Using `boundingRectWithSize...` returns the same size as by creating a UILabel and asking Auto Layout what it's size is with `systemLayoutSizeFittingSize:UILayoutFittingCompressedSize`. These sizes work perfectly with concretely-defined fonts, but with have heights that are consistently exactly 1 point too small when using any `[UIFont preferredFontForTextStyle:...]`

I also tried calculating the size by using Core Text as well as NSLayoutManager,  and both of THOSE return the same size, which works for both concrete fonts as well as `preferredFontForTextStyle`. However this size is frequently 2-6 points too tall when emojis are in the text.

I think both of these solutions are a bit better than the current code, which still frequently is an entire line height too tall. I'm still really put off by the 1-point shortage of the first solution, especially because it only happens when using `preferredFontForTextStyle` (even using the same font defined manually will work properly).

I think I want to do some more research with my own labels in a more sterile environment. I'm going to continue using my forked solution, because my app only uses custom fonts, but I don't feel that it's worth contributing to the main library until we have a solution that works for `preferredFontForTextStyle` without any magic pixels, especially considering how much Apple seems to want people to use that now.

**Comment by jessesquires** [comment] 2015-10-25 19:28
Thanks @rosslebeau ! :tada: :+1:

**Comment by ZhaofengWu** [comment] 2016-08-22 06:44
I still see this issue appearing.

Using the font 
`collectionView?.collectionViewLayout.messageBubbleFont = UIFont.systemFontOfSize(14)` 
and having the messages as
`var arr = [JSQMessage]()
var dotStr = ""
for _ in 0..<100 {
    dotStr += "."
    arr.append(JSQMessage(senderId: AvatarIDLeonard, displayName: getName(User.Leonard), text: dotStr))
}`,
when the dots fill EXACTLY a line, you will see that the margin for a new line is already made.

I only changed these two places of code on the SwiftExample project. This can be reproduced every time on iPhone 5S iOS 8.4, iPhone 5S iOS 9.3, iPhone 6 iOS 8.4, iPhone 6 iOS 9.3, and presumably many other hardware / iOS versions.
<img width="432" alt="screen shot 2016-08-22 at 2 40 26 pm" src="https://cloud.githubusercontent.com/assets/11954789/17845740/b5b2134a-6876-11e6-8bf0-ba349fdfd65b.png">
<img width="487" alt="screen shot 2016-08-22 at 2 42 17 pm" src="https://cloud.githubusercontent.com/assets/11954789/17845741/b5b22d44-6876-11e6-8588-1bd234db7686.png">
<img width="487" alt="screen shot 2016-08-22 at 2 39 56 pm" src="https://cloud.githubusercontent.com/assets/11954789/17845742/b5fe5e4e-6876-11e6-9553-6cb6654e156d.png">
<img width="432" alt="screen shot 2016-08-22 at 2 41 18 pm" src="https://cloud.githubusercontent.com/assets/11954789/17845744/b6eff614-6876-11e6-8e4d-5cf5cb674250.png">

**Comment by Mathimatica** [comment] 2016-10-24 22:01
Hey guys, forget using the horrible UI functions to figure out size use this instead: (Answer 2)

http://stackoverflow.com/questions/22916566/cant-seem-to-calculate-correct-line-height-of-nsattributedstring-for-a-uilabel

**Comment by Mathimatica** [comment] 2016-10-24 22:02
- (CGSize)rectForAttributedString:(NSAttributedString *)string withSize:(CGSize)theSize
{
    if (!string || CGSizeEqualToSize(theSize, CGSizeZero)) {
        return CGSizeZero;
    }

    // setup TextKit stack
    NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:theSize];
    NSTextStorage *textStorage = [[NSTextStorage alloc] initWithAttributedString:string];
    NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
    [layoutManager addTextContainer:textContainer];
    [textStorage addLayoutManager:layoutManager];

    // query for size
    CGRect rect = [layoutManager usedRectForTextContainer:textContainer];

    return CGSizeMake(ceilf(rect.size.width), ceilf(rect.size.height));
}

**Comment by Mathimatica** [comment] 2016-10-25 15:47
i made a UIFont extension that works 100% of the time and cool thing is u can use this off the main thread and calculate this asynch!!:

- (CGSize)rectForString:(NSString*)string withSize:(CGSize)size withLineFragmentPadding:(CGFloat)padding
{
    //https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/TextLayout/Tasks/StringHeight.html
    
    NSTextStorage *textStorage = [[NSTextStorage alloc] initWithString:string];
    NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:size];
    NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
    
    [layoutManager addTextContainer:textContainer];
    [textStorage addLayoutManager:layoutManager];
    
    [textStorage addAttribute:NSFontAttributeName value:self range:NSMakeRange(0, [textStorage length])];
    
    [textContainer setLineFragmentPadding:padding];
    
    (void) [layoutManager glyphRangeForTextContainer:textContainer];
    
    CGSize newSize = [layoutManager usedRectForTextContainer:textContainer].size;
    
    return CGSizeMake(ceilf(newSize.width), ceilf(newSize.height));
}

**Comment by promisenxu** [comment] 2016-11-04 04:04
@rosslebeau 😭 Your beautiful solution no longer works for me on iOS10 for some text. Why does it have to be so difficult?!!

@Mathimatica Thanks for the sample code - NSTextStorage, NSTextContainer and NSLayoutManager are all created each time a size is calculated - I guess that part can be optimized?

**Comment by apwelsh** [comment] 2016-11-04 04:31
This is what I use in my custom cell:

```
-(CGSize)textViewDisplaySizeForString:(NSString *) text withFront:(NSString *) fontName
{
    CGSize screen = [[UIScreen mainScreen] applicationFrame].size;
    CGSize size = CGSizeMake(screen.width - 80, screen.height);

    // This is where the magic happens.  
    CGRect rect = [text boundingRectWithSize:size 
                        options:NSStringDrawingUsesLineFragmentOrigin 
                        attributes:@{ NSFontAttributeName:fontName } 
                        context:nil];

    return rect.size;
}

```

What this does, is it returns the recommended CGSize that is required to make the supplied text fit into the target maximum width space, which I hard coded to screen.width - 80, to ensure each message has the appropriate offset.

**Comment by Mathimatica** [comment] 2016-11-04 20:45
@promisenxu yes
