### ISSUE TITLE
Chat box, keyboard problem

### ISSUE THREAD

**Issue by xiongcaixing1986** [jessesquires/JSQMessagesViewController#1466] opened 2016-02-26 06:17 UTC
In iOS 9, the keyboard disappeared more difficult, and there is no drag gesture

**Comment by jessesquires** [comment] 2016-02-26 15:18
thanks @xiongcaixing1986 ! :smile: 

closing this as a duplicate of #1063.

please make sure you follow our guidelines and complete the issue template next time.

**Closed by jessesquires** 2016-02-26 15:18 UTC
Labels: bug, duplicate

**Comment by xiongcaixing1986** [comment] 2016-02-29 01:44
thanks
