### ISSUE TITLE
Portrait image from camera is not showing with correct aspect ratio

### ISSUE THREAD

**Issue by betzerra** [jessesquires/JSQMessagesViewController#825] opened 2015-03-02 16:23 UTC
I'm getting this output when I take a picture using the camera on portrait:
![screen shot 2015-03-02 at 1 14 24 pm](https://cloud.githubusercontent.com/assets/681600/6444847/10341714-c0df-11e4-8457-9a8f0cd930ff.png)

And I swear that my head is taller than that :-)
Here's the image I got on `self.image` at this point at `JSQPhotoMediaItem`
```
- (UIView *)mediaView
{
    if (self.image == nil) {
        return nil;
    }
    
    if (self.cachedImageView == nil) {
        CGSize size = [self mediaViewDisplaySize];
        UIImageView *imageView = [[UIImageView alloc] initWithImage:self.image];
        imageView.frame = CGRectMake(0.0f, 0.0f, size.width, size.height);
        imageView.contentMode = UIViewContentModeScaleAspectFill;
        imageView.clipsToBounds = YES;
        [JSQMessagesMediaViewBubbleImageMasker applyBubbleImageMaskToMediaView:imageView isOutgoing:self.appliesMediaViewMaskAsOutgoing];
        self.cachedImageView = imageView;
    }
    
    return self.cachedImageView;
}
```

![screen shot 2015-03-02 at 1 12 56 pm](https://cloud.githubusercontent.com/assets/681600/6444861/29947ed8-c0df-11e4-88fe-7f98caeed8d1.png)

PS: Sorry for the grumpy face LOL

**Comment by jessesquires** [comment] 2015-03-02 18:09
thanks @betzerra !

closing as a duplicate of #740

**Closed by jessesquires** 2015-03-02 18:09 UTC
Labels: bug, duplicate
