### ISSUE TITLE
JSQMessagesCollectionViewIncoming memory error

### ISSUE THREAD

**Issue by niklas22** [jessesquires/JSQMessagesViewController#994] opened 2015-05-20 09:06 UTC
Hello everyone!

I'am currently creating a Chatapplication with JSQMessageViewController. Anyway all functions work well until the delete function. 

To my issue:
I have a tableView with all Chatpartner. If i click one, i'll get navigated to the JSQMessageViewController.

On a longpress event, i added a delete selector. 

i delete them like this:

    func deleteEntrybyIndexPath(indexPath: [NSIndexPath]) {
        self.collectionView?.performBatchUpdates({ () -> Void in
            self.appdel.user.chats[self.partnerIndex].removeMessageByIndex(indexPath[0].row, isMedia: self.isMedia)
            self.collectionView?.deleteItemsAtIndexPaths(indexPath)

        }, completion: nil)
    }

this works fine but when i navigate back to my tableView it crashes

After enabling zombie objects in the Diagnostics i get this error:

[JSQMessagesCollectionViewCellIncoming release]: message sent to deallocated instance 0x7fc76acf08b0.

I hope i displayed my issue properly, if there are any questions let me know.

**Comment by alezoffoli** [comment] 2015-06-12 18:03
I can confirm this happens to me too after long pressing a bubble, selecting a custom event, and then navigates back to my tableView. And my "custom event" doesn't do anything for now...

This doesn't happen if I select a normal action like Copy for example.

*** -[JSQMessagesCollectionViewCellOutgoing release]: message sent to deallocated instance 0x12fa57ac0

**Comment by jessesquires** [comment] 2015-06-15 18:48
thanks @alezoffoli for confirming this was the same as #1026 / #1027.

closing as resolved / dupe.

**Closed by jessesquires** 2015-06-15 18:48 UTC
Labels: bug, duplicate
