### ISSUE TITLE
On iOS 9 launched controller scrolling to the bottom with some delay

### ISSUE THREAD

**Issue by zigdanis** [jessesquires/JSQMessagesViewController#1260] opened 2015-10-14 19:17 UTC
I'm launching view controller and it is scrolling to the bottom with some delay. `automaticallyScrollsToMostRecentMessage` been set to `true`.
Here is the video, it's kinda hard to notice on the first time:
![ios9-delay-bug](https://cloud.githubusercontent.com/assets/1284116/10494829/423c35a4-72c1-11e5-9966-6e0380db1bdb.gif)

**Comment by jessesquires** [comment] 2015-10-15 01:20
Thanks @zigdanis !

This is a dupe of #780

**Closed by jessesquires** 2015-10-15 01:20 UTC
Labels: bug, duplicate
