### ISSUE TITLE
behavior of the UICollectionViewFlowLayout is not defined when rotating device

### ISSUE THREAD

**Issue by BillCarsonFr** [jessesquires/JSQMessagesViewController#881] opened 2015-03-24 14:49 UTC
Hi,

With the sample application, when i rotate the device, i can see the following logs (emulator 8.1):

```
2015-03-24 15:45:00.085 JSQMessages[98856:631617] the behavior of the UICollectionViewFlowLayout is not defined because:
2015-03-24 15:45:00.086 JSQMessages[98856:631617] the item width must be less than the width of the UICollectionView minus the section insets left and right values.
2015-03-24 15:45:00.086 JSQMessages[98856:631617] Please check the values return by the delegate.
```

The message view seems to work ok. Is there a way to fix this?

**Comment by jessesquires** [comment] 2015-03-24 16:46
Hey @BillCarsonFr - Yes I've seen this, though it is minor.

I'm not sure if this is a JSQMessages bug, or a UIKit bug. The `itemWidth` is determined dynamically in the collectionView delegate method, and the layout is invalidated before and after rotations.

It seems like `UICollectionViewLayout` is (incorrectly?) querying this delegate method at some point *during* the rotation, thus it (temporarily) thinks that it is in an inconsistent state.

**Comment by Mamong** [comment] 2016-02-01 14:01
#1042 Same bug

**Comment by kabiroberai** [comment] 2016-03-16 11:36
I'm making an iPad app with a split view controller, and for some reason, when I rotate my device's orientation to portrait, and then back to landscape, my messages get cut off and it logs the same error. I'm wondering whether I should create my own bug report, as mine didn't only log the error, it affected the layout as well.

**Comment by pikor** [comment] 2016-07-21 08:58
@kabiroberai you've ported code correctly and it works for me, however my iPad app is portrait so no rotations included.

**Comment by tethridge** [comment] 2017-02-14 19:03
I'd like to request that this issue priority be raised.  It is a pretty bad experience when using the framework on iPad within a split-view controller.  See the screen shot I've attached.  Let me know further explanation is needed.  This occurs every time the device is rotated.

![88zfa](https://cloud.githubusercontent.com/assets/6879838/22944292/3573b760-f2be-11e6-8354-8644fe19be2f.png)

**Comment by apwelsh** [comment] 2017-02-14 23:45
Have you inspected the collectionView frame.size after the rotation? I am curious if the issue if merely that the frame width is not properly correcting itself.  I uad a si illar issue where my custom control looked correct until I resized or moved it, then everything was bound to the wrong extent, causing the size to be adjusted to the margin position not the extents.  I ended up digging through the constraints until I found the one that was wrong. 

I dont use the chat view in landscape, i have my app locked in portrait mode, but thought this might help.. I know it is elementary, but we all make mistakes and sometime eaily overlook them...

**Comment by tethridge** [comment] 2017-02-15 21:04
I added some print statements in viewDidLayoutSubviews and the frame size seems to be correct after each rotation.  It seems to me that it is a problem with a cached value.  What is the recommended way to force the layout to recalculate everything again after a rotation?  I've tried several methods, but nothing has worked.
```
override func viewDidLayoutSubviews() {
        Log.d("XXX: -----------------------------------------")
        Log.d("XXX: Frame size: \(collectionView?.frame.size)")
        Log.d("XXX: Bounds: \(collectionView?.bounds.size)")
        Log.d("XXX: split view: \(splitViewController?.view?.frame.size)")
        Log.d("XXX: detail view: \(splitViewController?.viewControllers.last?.view?.frame.size)")
    }
```

Produced these log values:
```
[Log.swift|DEBUG] XXX: -----------------------------------------
[Log.swift|DEBUG] XXX: Frame size: Optional((447.5, 1024.0))
[Log.swift|DEBUG] XXX: Bounds: Optional((447.5, 1024.0))
[Log.swift|DEBUG] XXX: split view: Optional((768.0, 1024.0))
[Log.swift|DEBUG] XXX: detail view: Optional((447.5, 1024.0))
[Log.swift|DEBUG] XXX: -----------------------------------------
[Log.swift|DEBUG] XXX: Frame size: Optional((634.5, 768.0))
[Log.swift|DEBUG] XXX: Bounds: Optional((634.5, 768.0))
[Log.swift|DEBUG] XXX: split view: Optional((1024.0, 768.0))
[Log.swift|DEBUG] XXX: detail view: Optional((634.5, 768.0))
```

**Comment by tethridge** [comment] 2017-02-17 14:32
I'd also like to add that this is easily reproducible with the sample swift app.  You just need to throw a split view controller on the storyboard, set the chat view controller as the detail view controller, configure the messages so that they are initialized with a normal conversation using the helper method, and then set the split view controller as the starting view controller.  When run on an ipad or ipad simulator you see the issue.

**Comment by tethridge** [comment] 2017-04-14 20:55
Any update on this issue?  I had set it aside, but now I need to investigate it more.  Just wondering if any time has spent investigating it?  I can provide a sample project if needed.

**Comment by tethridge** [comment] 2017-04-25 13:21
I've uploaded a sample project that I'm using to debug this issue.  Check out: https://github.com/tethridge/rotation-issue-with-invalidation-context

I've got to get this issue fixed before I can release my project.  I would greatly appreciate any pointers as to why the frame width is incorrect when calculating itemWidth in JSQMessagesCollectionViewFlowLayout.m.  

I checked in the pod files to this sample project because I have added some logging print statements.  Feel free to delete the pods and pull unmodified source for JSQMessagesViewController.  I haven't modified the source except for the logging statements.

One interesting thing I've noticed is that on the iPad Air 2 and iPad Mini 2 I see this issue.  My buddy has an iPad 4 and he isn't seeing the issue.  It leads me to think that this may be a bug in iOS, so it may be that we need to work around a bug if possible.

**Comment by jasonn85** [comment] 2017-05-04 22:35
I don't know if this is related, but I had the same problem as @kabiroberai with a split view and the bubbles being cut off.  I solved that by overriding my  `viewWillTransitionToSize:withTransitionCoordinator:` to invalidate the layout during the transition itself, similarly to the fix suggested in https://github.com/jessesquires/JSQMessagesViewController/issues/1042

```
// This is a fix for a layout invalidation bug, specifically only seen so far in iPad builds inside of a split view.
// Similar to:  https://github.com/jessesquires/JSQMessagesViewController/issues/1042 and https://github.com/jessesquires/JSQMessagesViewController/issues/881

@interface JSQMessagesViewController (Fix_For_iPad_Rotation)

- (void)jsq_resetLayoutAndCaches;

@end

@implementation YourConversationViewClass (Fix_For_iPad_Rotation)

- (void) viewWillTransitionToSize:(CGSize)size withTransitionCoordinator:(id<UIViewControllerTransitionCoordinator>)coordinator
{
    [coordinator animateAlongsideTransition:^(id<UIViewControllerTransitionCoordinatorContext>  _Nonnull context) {
        [super jsq_resetLayoutAndCaches];
    } completion:nil];
    [super viewWillTransitionToSize:size withTransitionCoordinator:coordinator];
}

@end
```


So far I have not been able to get rid of the `UICollectionViewFlowLayoutBreakForInvalidSizes` warnings.  As Jesse said, the calculations are done once prematurely with the old frame, causing all of the warnings, then they are done again immediately afterward to make all good in the world.  The only apparently downside is the log spam.

**Comment by 0xPr0xy** [comment] 2017-06-23 07:45
Fixed it like this in swift, saves me exposing the private method `jsq_resetLayoutAndCaches`
```
    override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        coordinator.animate(alongsideTransition: { (_) in
            NotificationCenter.default.post(name: NSNotification.Name.UIDeviceOrientationDidChange, object: nil)
        }, completion: nil)

        super.viewWillTransition(to: size, with: coordinator)
    }
```

**Comment by jessesquires** [comment] 2017-07-17 02:27
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:27 UTC
Labels: bug, priority: low
