### ISSUE TITLE
System status messages

### ISSUE THREAD

**Issue by alexcfaber** [jessesquires/JSQMessagesViewController#891] opened 2015-03-30 13:31 UTC
I am currently using JSQMessagesViewController in an app and I couldn't be more pleased. Great work all around. In our app we are also using statusmessages such as 'X has left the chat' etc. 

We tried doing this in two ways:

1) Creating a custom bubble, black background and all round. This works great, our only issue is alignment. We'd love to have it dead center instead of being shows as an Incoming message. 

2) Using the top label of the cell (where the time is shown). This option gives us more of the layout we want, the bubble is in the center. However it's also the full width. It also limits our option on using the time field.

We've stuck to option 1 for the time being, but it's something we would love to update as it just looks more aesthetically pleasing if it's aligned properly. According to Issue 321 it is something thats coming (soon?). Any possibility of insight in to how soon, soon is? or even better, what would be the best way to override the layout for one of the incoming bubbles?

**Comment by jessesquires** [comment] 2015-03-30 16:16
closing as duplicate of #321 

@alexcfaber - there's a comment on that thread with details for how to do this in the current framework.

**Closed by jessesquires** 2015-03-30 16:16 UTC
