### ISSUE TITLE
dequeueLoadEarlierMessagesViewHeaderForIndexPath crash

### ISSUE THREAD

**Issue by DongjieLi** [jessesquires/JSQMessagesViewController#1002] opened 2015-05-26 03:32 UTC
![screen shot 2015-05-26 at 11 31 04 am](https://cloud.githubusercontent.com/assets/7219185/7804804/c962205c-039a-11e5-8fe8-921de2b1e1cf.png)

**Comment by jessesquires** [comment] 2015-05-26 03:41
please provide steps on how to reproduce, plus library and iOS version numbers.

**Comment by DongjieLi** [comment] 2015-05-26 03:57
Thank you quick  reply
```
- (void)scrollViewDidScroll:(UIScrollView)scrollView {
    ......
     JSQMessagesLoadEarlierHeaderView *headerView;
    if ([[self.collectionView dequeueLoadEarlierMessagesViewHeaderForIndexPath:[NSIndexPath indexPathForItem:0 inSection:0]] isMemberOfClass:[JSQMessagesLoadEarlierHeaderView class]]) {
                headerView = [self.collectionView dequeueLoadEarlierMessagesViewHeaderForIndexPath:[NSIndexPath indexPathForItem:0 inSection:0]];
            }
            [headerView.loadActivityIndicatorView startAnimating];   // custom activity 
   // load data
    ......
}
```
sometimes crash at "dequeueLoadEarlierMessagesViewHeaderForIndexPath:".

**Comment by jessesquires** [comment] 2015-05-26 04:40
thanks @DongjieLi - closing, since this is not part of the library. StackOverflow would be a better place for this question.

**Closed by jessesquires** 2015-05-26 04:40 UTC
