### ISSUE TITLE
inputToolbar not showing and collectionView scrolling down when appeared modal VC

### ISSUE THREAD

**Issue by Ryskalo** [jessesquires/JSQMessagesViewController#1873] opened 2016-10-18 13:15 UTC
iOS version: 10
Library version: 7.3.4

In first present all is OK
![photo_18_10_16__15_54_16](https://cloud.githubusercontent.com/assets/8089884/19478975/50246722-954d-11e6-8cfb-af3efd483e89.jpg)

When I closed VC and open again (It happens only when I send message)
![photo_18_10_16__15_54_25](https://cloud.githubusercontent.com/assets/8089884/19478981/592fe3f0-954d-11e6-8c0d-ec6092bf680b.jpg)

When I scroll up, I see my message
![photo_18_10_16__15_54_29](https://cloud.githubusercontent.com/assets/8089884/19478985/5dd6adf8-954d-11e6-9656-cc990dfff843.jpg)

this does not happen if in chat are incoming messages only

**Comment by gmansata6290** [comment] 2016-10-22 14:39
@jessesquires , @eliburke Thanks for the wonderful library you  provided to us.

I am facing the similar issue in my app also. So to replicate this issue I have attach a demo code.
[JSQMessagesViewController-develop 2.zip](https://github.com/jessesquires/JSQMessagesViewController/files/545832/JSQMessagesViewController-develop.2.zip)

1) There are 2 issues I m facing. i) If I m showing fullscreen popup view on top of the ChatViewController, the inputToolBar is still visible. 
ii) If I try to use any inputView like keyboard or pickerView as textField inputViews inside the fullScreen popup view, the inputToolbar vanishes.  

Use Swift Example as project for the demo

So In demo follow the Step to reproduce the above issues.
1) Tap on Any MessageBubble, it will show a fullscreen blurView with button as Close and a textField.
2) If you click inside the textField, the keyboard will be shown and then when you click the close button the blur view will go away as well as the input toolbar.
3) Again Tap on Any MessageBubble and click on close, the inputToolbar will not go away. 


So I just want to know the reason and how to resolve this issue? Your help would really appreciated.

**Comment by jessesquires** [comment] 2017-07-17 02:24
Hello everyone!

I'm sorry to inform the community that I'm officially deprecating this project. 😢 Please read my blog post for details:

http://www.jessesquires.com/blog/officially-deprecating-jsqmessagesviewcontroller/

Thus, I'm closing all issues and pull requests and making the necessary updates to formally deprecate the library. I'm sorry if this is unexpected or disappointing. Please know that this was an extremely difficult decision to make. I'd like to thank everyone here for contributing and making this project so great. It was a fun 4 years. 😊 

Thanks for understanding,
— jsq

**Closed by jessesquires** 2017-07-17 02:24 UTC
Labels: questions & help
