### ISSUE TITLE
When first time load the JSQMessageViewController the bubble width increase

### ISSUE THREAD

**Issue by saurabhaceitj** [jessesquires/JSQMessagesViewController#1974] opened 2017-01-05 07:22 UTC
When load the jsq message view controller it the bubble width increase, after orientation it's working fine, but first time give problem.

At first time screen shot is:
![screen shot 2017-01-05 at 12 40 33 pm](https://cloud.githubusercontent.com/assets/21302249/21672072/c1cd8e22-d345-11e6-8385-020d1f9532c9.png)

**Comment by ko0f** [comment] 2017-01-11 06:37
It's caused by a bad collectionView.frame size when appearing, it has the xib's width (375) instead of current device's width.

May not be the perfect solution, but it can be resolved by simply using UIDevice.main.bounds instead.

https://github.com/ko0f/JSQMessagesViewController/commit/f60711a15f00c9a552b017caea3ec293805c4438

**Comment by itolisto** [comment] 2017-01-12 07:14
I'm having the same issue, there isn't a tested solution yet? 

![simulator screen shot jan 12 2017 00 42 28](https://cloud.githubusercontent.com/assets/11670462/21880325/ffd4a692-d863-11e6-8808-9b4ced6c70a5.png)

**Comment by mike3osei** [comment] 2017-03-22 01:25
I have this same issue any news on a fix for this?

**Comment by alessioarsuffi** [comment] 2017-03-22 10:04
how do you load and show your CollectionView?

**Comment by mike3osei** [comment] 2017-03-22 11:02
The same way given in the swift example. In view did load.

`` override func viewDidLoad() {
        super.viewDidLoad()
        
...
              
        self.topContentAdditionalInset = 77;
...
    
        incomingBubble = JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: UIEdgeInsets.zero).incomingMessagesBubbleImage(with: Color.grey.lighten3)
        
        outgoingBubble = JSQMessagesBubbleImageFactory(bubble: UIImage.jsq_bubbleCompactTailless(), capInsets: UIEdgeInsets.zero).outgoingMessagesBubbleImage(with: Color.grey.lighten1)
        
        
        self.inputToolbar?.contentView?.leftBarButtonItem?.setImage(UIImage(named: "cm_photo_camera_white")?.withRenderingMode(.alwaysTemplate), for: .normal)
        
        self.inputToolbar?.contentView?.leftBarButtonItem?.imageView?.contentMode = UIViewContentMode.scaleAspectFit

        self.inputToolbar.contentView.rightBarButtonItem = nil
        
         self.inputToolbar?.contentView?.leftBarButtonItem?.tintColor = Color.grey.base
        
        
        self.inputToolbar.layer.borderWidth = 0;

        self.inputToolbar?.contentView?.backgroundColor = UIColor.white
        
        
        self.inputToolbar?.contentView?.textView?.placeHolder = "New Message"

        self.inputToolbar?.contentView?.textView?.layer.borderColor = UIColor(white: 0.0, alpha: 0.21).cgColor
        self.inputToolbar?.contentView?.textView?.layer.borderWidth = 1.0
        self.inputToolbar?.contentView?.textView?.layer.cornerRadius = 14.0
        
        self.inputToolbar?.contentView?.textView?.delegate = self
        self.inputToolbar?.contentView?.textView?.returnKeyType = UIReturnKeyType.send

        self.inputToolbar?.clipsToBounds = true
        
        
        
        self.senderId = String(currentUser.id)
        
        self.senderDisplayName = currentUser.name
        
        
        collectionView.collectionViewLayout.messageBubbleTextViewFrameInsets = UIEdgeInsetsMake(5, 5, 5, 5)
        collectionView.collectionViewLayout.messageBubbleLeftRightMargin = 20;
        
        
        collectionView?.collectionViewLayout.incomingAvatarViewSize = .zero
        collectionView?.collectionViewLayout.outgoingAvatarViewSize = .zero

        collectionView?.collectionViewLayout.springinessEnabled = false
        collectionView?.frame = UIScreen.main.bounds
        
        
        automaticallyScrollsToMostRecentMessage = true
        
       
        loadMessages()
        
        self.collectionView?.reloadData()
        self.collectionView?.layoutIfNeeded()
    }`

**Comment by jessesquires** [comment] 2017-04-07 00:33
Thanks all!

The fix in #985 should help!

**Closed by jessesquires** 2017-04-07 00:33 UTC
Labels: questions & help
