### ISSUE TITLE
When scrolling the texts in collectionView, it's not very smooth. But the situation didn't appear when scrolling the images in collectionView.

### ISSUE THREAD

**Issue by ijinmao** [jessesquires/JSQMessagesViewController#860] opened 2015-03-14 12:37 UTC
Why scrolling the text collection view cell is not smoother than scrolling the image collection view cell?
![image](https://cloud.githubusercontent.com/assets/8135815/6651983/d59c7fe2-ca98-11e4-9437-d21c040237fc.png)
![image](https://cloud.githubusercontent.com/assets/8135815/6651987/e58524d6-ca98-11e4-9a1d-7e7420765804.png)

**Comment by jessesquires** [comment] 2015-03-14 18:20
dupe of #492

**Closed by jessesquires** 2015-03-14 18:20 UTC
Labels: bug, duplicate
