### ISSUE TITLE
Warning about NSLayoutConstrain .  on release 7.2.0

### ISSUE THREAD

**Issue by tuanpa199** [jessesquires/JSQMessagesViewController#1240] opened 2015-10-04 10:14 UTC
I spam text messages and scroll down/up, on an iPhone 6s simulator
<img width="1265" alt="screen shot 2015-10-04 at 5 01 40 pm" src="https://cloud.githubusercontent.com/assets/4744234/10267332/0e4b6bfc-6aba-11e5-879f-d6b6912199d2.png">

**Comment by harlanhaskins** [comment] 2015-10-04 14:01
This is a dupe of #817, but deserves another look.

**Comment by jessesquires** [comment] 2015-10-04 21:50
Yep, closing as duplicate of #817.

Thanks @tuanpa199 ! :smile: Please review the [contribution guidelines](https://github.com/jessesquires/JSQMessagesViewController/blob/develop/CONTRIBUTING.md).

Thanks @harlanhaskins !

**Closed by jessesquires** 2015-10-04 21:50 UTC
Labels: bug, duplicate
