### ISSUE TITLE
MessageBubbleTopLabel different heights in each cell

### ISSUE THREAD

**Issue by bitomule** [jessesquires/JSQMessagesViewController#1671] opened 2016-06-13 11:31 UTC
I'm trying to display user name only on some cells but I get an Autolayout Issue. I think it's because cell are reused and it's trying yo use a cell with a different height. I get this auto layout issue:

```
(
    "<NSAutoresizingMaskLayoutConstraint:0x7fa971fe5ba0 h=--& v=--& V:[UIView:0x7fa971fd2050(38)]>",
    "<NSLayoutConstraint:0x7fa971fd2490 V:[JSQMessagesLabel:0x7fa971fd21c0(30)]>",
    "<NSLayoutConstraint:0x7fa971fd2d60 V:[JSQMessagesLabel:0x7fa971fd2a00(20)]>",
    "<NSLayoutConstraint:0x7fa971fddb90 V:[JSQMessagesLabel:0x7fa971fdd890(0)]>",
    "<NSLayoutConstraint:0x7fa971fde200 V:|-(0)-[JSQMessagesLabel:0x7fa971fd21c0]   (Names: '|':UIView:0x7fa971fd2050 )>",
    "<NSLayoutConstraint:0x7fa971fde2f0 V:[JSQMessagesLabel:0x7fa971fd21c0]-(0)-[JSQMessagesLabel:0x7fa971fd2a00]>",
    "<NSLayoutConstraint:0x7fa971fde390 V:[JSQMessagesLabel:0x7fa971fd2a00]-(0)-[UIView:0x7fa971fd30e0]>",
    "<NSLayoutConstraint:0x7fa971fde430 V:[UIView:0x7fa971fd30e0]-(0)-[JSQMessagesLabel:0x7fa971fdd890]>",
    "<NSLayoutConstraint:0x7fa971fde4d0 V:[JSQMessagesLabel:0x7fa971fdd890]-(0)-|   (Names: '|':UIView:0x7fa971fd2050 )>"
)
```

Seems like NSAutoresizingMaskLayoutConstraint is ignoring MessageBubbleTopLabel height. If I return 12 instead of 0 in heightForMessageBubbleTopLabelAtIndexPath when user name is not displayed it works without issues but I get an empty space between each cell.

Any idea why this happens?

**Comment by jessesquires** [comment] 2016-06-14 15:22
closing as duplicate of #817

**Closed by jessesquires** 2016-06-14 15:22 UTC
Labels: bug, duplicate
