### ISSUE TITLE
Scrolling perfomance on iOS8

### ISSUE THREAD

**Issue by igrekde** [jessesquires/JSQMessagesViewController#492] opened 2014-09-16 11:15 UTC
I've encountered a strange behaviour on iOS8. When I scroll the collectionView on the device with iOS8 GM, it performs with some lags, while on another device with iOS 7.1 everything is fine. 
Is it a well-known issue?

**Comment by mohpor** [comment] 2015-02-02 05:12
I've tried this but only to find that `TTTAttributedLabel` doesn't support `NSTextAttachment`s and therefor it is futile to go through this if you want to have something like smilies in your text.
Read more: TTTAttributedLabel/TTTAttributedLabel/issues#447

**Comment by mohpor** [comment] 2015-02-02 09:13
Gotta admit, opting out of auto-layout improves the scrolling performance so much it seems the only way for now. Although current implementation of manual layout suggested by https://gist.github.com/galambalazs/8d70309e5a112e9a138f isn't complete (especially cellBottomLabel sizing and whatnots), but it's nothing compared to the length we have to go to improve performance with auto-layout!

**Comment by jessesquires** [comment] 2015-02-02 16:55
Thanks for the input @mohpor !

Regarding `TTTAttributedLabel`'s lack of support for `NSTextAttachment` — doesn't this not matter, given the media message framework?

**Comment by mohpor** [comment] 2015-02-02 17:03
of course it matters, media message is one thing but the lack of inline UIImage is something else. Without inline images, there will be no smilies!






—

**Comment by LeoNatan** [comment] 2015-02-02 17:14
Usually smilies are emoji characters, implemented using Unicode and the drawing system renders it's ownnicons there, with no need for text attachments. While the problem is there, it's sideline issue. I'd say performance is more important.

**Comment by mohpor** [comment] 2015-02-02 17:19
I wish it was that simple, if you were to support multi-platform messaging and wanted to implement your unique Smilies, you’d need those attachments. I’m not all against TTTAttributedLabel, I’m just pointing out its caveats.

Plus, I might have found a solution to improve performance so much  that may resolve all these problems  around performance. I have achieved near silk smooth performance even with text attachments in UITextView now, but I’m going to push it to the limits and then share it with you guys too.


—

**Comment by LeoNatan** [comment] 2015-02-02 17:21
Cool. Did you remove autolayout? =]

**Comment by mohpor** [comment] 2015-02-02 17:22
Of course I did! It was my first step. It helped so much I was going to cry out of happiness! :D


—

**Comment by victorcampeanu** [comment] 2015-02-05 17:39
any updates on the new versions?

**Comment by xidazheng** [comment] 2015-02-05 20:25
Curious if anyone has looked into using inputAccessoryView?  http://derpturkey.com/uitextfield-docked-like-ios-messenger/
https://developer.apple.com/library/prerelease/ios/documentation/StringsTextFonts/Conceptual/TextAndWebiPhoneOS/InputViews/InputViews.html

**Comment by anilanar** [comment] 2015-02-08 11:08
@jessesquires 
I was a believer of autolayout but recently I've seen a tech-talk by a Facebook dev and learnt that autolayout is banned at Facebook. After encountering multiple issues here related to it and also to give AsyncDisplayKit (doesn't support autolayout) a try, I decided to remove all autolayout stuff and nibs from JSQMessagesViewController. 
And guess what? I can enforce the very same constraints without actually using autolayout.

Here is an example for `JSQMessagesToolbarContentView`:
```
CGRect frame = self.bounds;
CGRect leftContainerFrame = CGRectMake(8.0f, 6.0f, self.leftBarButtonContainerViewWidthConstraint, 32.0f);
self.leftBarButtonContainerView.frame = leftContainerFrame;
    
CGRect rightContainerFrame = CGRectMake(frame.size.width - (8.0 + self.rightBarButtonContainerViewWidthConstraint), 6.0f, self.rightBarButtonContainerViewWidthConstraint, 32.0f);
self.rightBarButtonContainerView.frame = rightContainerFrame;
    
UIEdgeInsets textViewInsets = UIEdgeInsetsMake(7.0f, CGRectGetMaxX(leftContainerFrame) + 8.0f, 7.0f, frame.size.width - CGRectGetMinX(rightContainerFrame) + 8.0f);
self.textView.frame = UIEdgeInsetsInsetRect(frame, textViewInsets);
```

This is equivalent to what autolayout was doing. One problem might arise if some constraints have inequalities but that can be solved too with simple math. None of the constraints are too complex and even if there was a really complex one, I guess its performance would have been horrible.

My point is, maybe autolayout can really be dropped.

**Comment by mohpor** [comment] 2015-02-08 11:14
@anilanar is right, but for me it's not a theory anymore, I have successfully re-implemented everything without auto layout ,using ASDK and batch updates instead of collection view's reload and the performance is much much better now.

**Comment by jessesquires** [comment] 2015-02-08 20:37
I agree, and I'm aware of all of the above. 

But here's what's most frustrating:
We **had** great performance **with** auto-layout. This is a regression in iOS 8. :cry:

As the author and maintainer, I need to deeply consider the kinds of fundamental changes suggested here, and plan accordingly (build out a roadmap). Major changes, or any breaking API changes, mean new major version releases (i.e. v6.x to v7.0). And then we have to live with those changes until the next major release (i.e. v8.0). Introducing new dependencies increases complexity in general and for devs using this library. Also, a lot of people are using this library — so it's also good to consider the most user-friendly approach to *any* major change.

Others have noted that moving away from `UITextView` and using `TTTAttributedLabel` has resolved these issues. Currently, I'm leaning toward this solution for a few reasons.

1. Aside from performance, there are *other* issues with `UITextView` (#747, #613, #438). Given these, I think moving to `TTTAttributedLabel` is inevitable.
2. Swapping out a `UITextView` for a `UILabel` is a pretty benign change. We basically preserve all the current semantics and functionality. 
3. On the other hand, using `AsyncDisplayKit` requires some fundamental architectural changes.
4. For current consumers of this API, `TTTAttributedLabel` will be easiest to understand and adapt to.

Now, for all the `AsynDisplayKit` advocates here :smile: , I'm not suggesting this will *never* be an option. But these are my current thoughts for the library's roadmap to version 7.0. Furthermore, there **are** some architectural changes I would like to make for v7.0 (see #453). Integrating `AsyncDisplayKit` on top of all these changes would be too much. But, maybe `AsyncDisplayKit` would make the cut for v8.0.

**Comment by mohpor** [comment] 2015-02-09 07:05
Thanks @jessesquires for the insight to the future.
I for one, have the utmost respect for you and your work and by no means I wanted to deny your right to decide the future of this wonderful framework, I just shared what I've found about a solution.
Now some notes from an AsyncDisplayKit advocate :smile: : Re-impleneting everything using AsyncDisplayKit would mean more than refactoring and tweaking, it means RE-IMPLEMENTING everything, because it is just not worth it otherwise and to be fair, I've started such thing and so far, it doesn't look good! :disappointed:, it is unstable, it is perilous to reload or redraw, it flickers most of the time and many many many more shortcomings I haven't even faced yet. BUT, there are aspects that could mean a lot if we switch to that have a noticeable performance difference. e.g. changing some factories to use `ASImageNode` instead of `UIIMageView`, because they are perfectly encapsulated and if developers have been using this framework correctly, they shouldn't feel anything! although it requires us to rethink the current reload mechanism :confounded:! In a real world application, the collection view may face around 2-10 reloads per second (in an active chat) that means a lot of performance if we reload the entire collection view!

One final though on this is that I think the pressure of maintaining this framework is unfair on just one person and we all should contribute more and improve this wonderful project.

**Comment by jessesquires** [comment] 2015-02-09 07:23
@mohpor 
<img src="http://s3.amazonaws.com/ragefaces/b50a224ee8948d6fd1987d3172f01017.png" width="250px", height="auto"/>

**Comment by DevonBoyer** [comment] 2015-02-09 12:40
I have been playing around with trying to fix the choppy scrolling, and one thing that fixed it in my own implementation is when configuring layout attributes:

```objectiveC
layoutAttributes.cellTopLabelHeight = [self.collectionView.delegate collectionView:self.collectionView
                                                                                layout:self
                                                      heightForCellTopLabelAtIndexPath:indexPath];
    
layoutAttributes.messageBubbleTopLabelHeight = [self.collectionView.delegate collectionView:self.collectionView
                                                                                         layout:self
                                                      heightForMessageBubbleTopLabelAtIndexPath:indexPath];
    
layoutAttributes.cellBottomLabelHeight = [self.collectionView.delegate collectionView:self.collectionView
                                                                                   layout:self
                                                      heightForCellBottomLabelAtIndexPath:indexPath];`

```

For me what I was doing was in the implementation of these methods was calculating the stringRect size, which means that these calculations are not getting cached and are being calculated every time the layout is invalidated. Either changing these to a constant value or caching these values greatly improved my performace (not perfect but definitely better). Hope this helps anyone :)

**Comment by soleares** [comment] 2015-02-22 05:07
@jessesquires at this point I wonder if it's worth using a TSI and getting some feedback from DTS.

**Comment by kartikthapar** [comment] 2015-03-12 03:31
So as it happens, I have been field testing the application a bit. Response is that the message view is really laggy overall. Some have also claimed that they feel they are using Android if they still in the message view for a while. Is there any progress on this? @jessesquires Please let me know how I can help as I am happy to spend some time (at most a weak) investigate a potential fix for iOS 8. Thanks. :)

**Comment by BillCarsonFr** [comment] 2015-03-12 14:40
Hi guys,

I currently have an iPhone 5c with iOS 7.1.2 and another iPhone 5c with iOS 8.1.3.
I just modified the sample project to add some more messages, and i ran timeProfiler on both. I just open the message view and do 12 back and forth.

You can have a quick look at the profile here, we clearly see the difference between iOS7 and 8 (it's smooth on iOS7):

iOS 7:
![timeprofiler_ios7](https://cloud.githubusercontent.com/assets/9841565/6618572/0fdc0bc2-c8c4-11e4-9237-f8845ef3826c.png)

iOS 8:
![timeprofiler_ios8](https://cloud.githubusercontent.com/assets/9841565/6618578/215e832a-c8c4-11e4-8c5c-dc360875be79.png)

In iOS8 there is like no difference between the first layout and the subsequent ones. 
I am new to Instruments, and i am still trying to understand better. But what i can see is that there is a difference in the call tree in iOS8.

For example i can see this in iOS7

    Running Time	Self	 
    1020.0ms   19.2%	0,0	   -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:]
    1017.0ms   19.2%	1,0	    -[DemoMessagesViewController collectionView:cellForItemAtIndexPath:]
    3.0ms       0.0%	0,0	    -[UICollectionView _addControlledSubview:atZIndex:]


and this in iOS8

    Running Time	Self	 
    3620.0ms   37.8%	1,0	   -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:]
    2593.0ms   27.0%	1,0	    -[UICollectionReusableView preferredLayoutAttributesFittingAttributes:]
    1011.0ms   10.5%	0,0	    -[DemoMessagesViewController collectionView:cellForItemAtIndexPath:]
    8.0ms       0.0%	0,0	    -[UICollectionView _addControlledSubview:atZIndex:]
    3.0ms       0.0%	1,0	    -[JSQMessagesCollectionViewLayoutAttributes isEqual:]
    1.0ms       0.0%	1,0	    objc_getProperty_non_gc(objc_object*, objc_selector*, int, signed char)
    1.0ms       0.0%	1,0	    -[UICollectionReusableView _wasDequeued]
    1.0ms       0.0%	1,0	    -[UICollectionReusableView _layoutAttributes]
    1.0ms       0.0%	1,0	    objc_autoreleaseReturnValue

The new call to preferredLayoutAttributesFittingAttributes is taking a lot of time.
Does this talk to someone?
Are there any changes or known issues with autoLayout in iOS8?

I am trying to drill this down.

**Comment by BillCarsonFr** [comment] 2015-03-12 14:55
If i modify JSQMessagesCollectionViewCell.m and just return the given layoutAttributes, it's not chunky anymore (but not as fluid iOS7 though).

    - (UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes
    {
        return layoutAttributes;
    }

**Comment by jessesquires** [comment] 2015-03-12 16:04
@BillCarsonFr excellent work! thanks! :+1: 

These changes have to do with the new self-sizing cells in iOS 8. That's what `preferredLayoutAttributesFittingAttributes:` is for.

Great information. I'll be looking into this.

**Comment by kartikthapar** [comment] 2015-03-15 03:54
@jessesquires Is there any update regarding the inclusion of `TTTAttributedLabel`? Just wondering if this was investigated at some point?

**Comment by ijinmao** [comment] 2015-03-15 04:18
@kartikthapar @jessesquires I changed the JSQMessagesCellTextView from UITextView to TTTAttributedLabel. Although I still feel lags, the scrolling performance greatly improved.

**Comment by jessesquires** [comment] 2015-03-17 01:40
Hey @kartikthapar -- the plan is to eventually switch to `TTTAttributedLabel` see [my comment above](https://github.com/jessesquires/JSQMessagesViewController/issues/492#issuecomment-73430267) for why.

**Comment by kartikthapar** [comment] 2015-03-17 02:15
That sounds really solid. I am happy to contribute in whatever capacity is needed. Thanks @jessesquires. Great work.

**Comment by jessesquires** [comment] 2015-03-17 02:54
:+1: pushing v7.0 today/tonight

**Comment by kartikthapar** [comment] 2015-03-17 03:04
Woh!! Yay

— Kartik Thapar

**Comment by jessesquires** [comment] 2015-04-09 04:22
Hello all — good news!

Testing on iOS 8.3, iPhone 5, latest on develop — scrolling is smooth for me in the demo project. This issue appears to be fixed, or at least significantly improved.

Can anyone else confirm?

**Comment by mohpor** [comment] 2015-04-09 09:25
Hi jesse,

When i saw the release note of iOS 8.3, I thought to myself, it probably has to do something with our issue!

I have moved from this project to implement my own using UITableView (after a long R&D phase it seemed inevitable, especially with all the problems collectionView has with FRC). But I'm sure it'll make my implementation easier now!

Good luck



—

**Comment by LeoNatan** [comment] 2015-04-09 09:31
@jessesquires The only thing that helped performance was the self-sizing fix someone mentioned.

```- (UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes
{
    return layoutAttributes;
}```

This fixed the scrolling issue for the most part in all iOS 8 devices.

**Comment by jessesquires** [comment] 2015-04-19 18:05
Closing this issue as resolved, per comments above.

However, moving to TTTAttributedLabel is still on the roadmap for a future release.

**Closed by jessesquires** 2015-04-19 18:05 UTC
Labels: bug, priority: high

**Comment by kartikthapar** [comment] 2015-04-20 04:26
I haven't tested this completely but it does feel much better. Congratulations!!

**Comment by csilouanos** [comment] 2015-05-25 11:56
I am trying to apply this cool library on my app but it seems that on iPhone 5 iOS 8.3 the issue with smooth scrolling still happens. @jessesquires I can send you a video to see it. I am not satisfied with the scrolling. Although we have tested it on iPhone 6 and it seems that works very good.

**Comment by galambalazs** [comment] 2015-06-26 11:47
I still have to use my manual layout fork.

@jessesquires did you file a radar about this? I'd like *everybody* in this thread to dupe the hell out of it! We are many and we are strong :)

Here are 2 videos demonstrating it on my 5S, iOS 8.3 using the latest develop branch (91e74b0f7b0059e8f25fb106b76de77d5c6703cf): 

https://www.dropbox.com/s/2wke30hqxtw6poa/JSQScrolling_iOS_v8_3.mov?dl=1
https://www.dropbox.com/s/cw57yku1qpy0y7m/JSQScrolling_fast_iOS_v8_3.mov?dl=1

And the 5S is a beast in terms of performance. 

There is clearly a regression on Apple's part that we have to get them to fix.

**Comment by LeoNatan** [comment] 2015-06-26 11:49
Not fixed as of iOS 9 beta 2. Scrolling is still terrible.

**Comment by galambalazs** [comment] 2015-06-26 11:55
This project has 5000+ stars, one of the most popular Objective-C repo on Github. 

I just got the Chromium team to fix a 5 year bug by guiding some of my users to their issue tracker. Sometimes you have to shower these big whales with bug reports in order to listen.

**Comment by galambalazs** [comment] 2015-06-29 17:00
Can you guys test this PR for scrolling performance? 
https://github.com/jessesquires/JSQMessagesViewController/pull/1058

Make sure to disable dataDetectors when testing it so you can see the improvements not affects by them.
 
They seem to be the biggest reason left to cause occasional jankiness.

**Comment by galambalazs** [comment] 2015-07-01 19:24
Just had a breakthrough with data detectors. Created  a PR for TTT and it blows UITextView away.
Creating labels and setting data detectors:

 **UITextView (1.662s)** *vs* **TTT (0.084s)**

https://github.com/TTTAttributedLabel/TTTAttributedLabel/pull/548#issuecomment-117799724

![datadetector](https://cloud.githubusercontent.com/assets/309987/8462974/9bb5e724-2037-11e5-8481-08591d32440d.png)

**Comment by LeoNatan** [comment] 2015-07-01 19:35
@galambalazs That's a terribly inaccurate and misleading test. What you actually measured is the creation of a text views, rather than data detectors logic cost. Data detectors are actually calculated on a background thread that doesn't even complete its run, if it even gets to run at all in your example, because the text view object is released just after allocation.

**Comment by LeoNatan** [comment] 2015-07-01 19:36
@jessesquires I think this issue needs to be reopened. The scrolling performance is still bad compared to other messaging apps such as WhatsApp, FB Messenger and Telegram.

**Comment by galambalazs** [comment] 2015-07-01 20:00
Haha fair enough, you may think I haven't tested it enough. I've been working on JSQ & TTT for the past few days however. :)

The whole point is moving data detection **logic** to the background thread! No reason to do it on the main thread. But that was possible with TTTAttributedLabel before. 

But in the old TTTLabel **allocation** of every detector instance ran on the Main thread. One for each label! This is what my PR is about. In the new version the "Label + detector creation" is now much faster. That's what the test screen shows.

I'll upload a JSQ fork in a minute for you to test. :)

**Comment by LeoNatan** [comment] 2015-07-01 20:06
That's not what I said. I said your testing methodology in the above example is wrong. `UITextView` already performs detector work on a low priority background queue. The test you show above is absolutely wrong. I make no claim that `UITextView` is more performant than `TTTAttributedLabel`, and indeed it may be much slower, but the test above is not what proves it.

**Comment by galambalazs** [comment] 2015-07-01 20:25
See my friend, it's just that you happen to be uninformed on that one. If you actually test it, UITextView data detectors do a ton of things on the Main thread. Painfully. Slow.

(now, where the actual regexes run might be another question, but seeing the net effect on the main thread, who cares?)


![ddtextkit](https://cloud.githubusercontent.com/assets/309987/8464086/f040e20a-203f-11e5-9dad-d1bac6b3649b.png)

(testing 1500 UITextViews with short random text, urls, phone numbers. It's all shown on screen in a scrollview, nothing is deallocated).

**Comment by galambalazs** [comment] 2015-07-01 20:35
Popcorn time! ;)

TTT after new Pull Request: https://www.dropbox.com/s/8bdiwhjepxznbsd/ttt.mov?dl=1
UITextView: https://www.dropbox.com/s/rkldfwert98wtly/uitextview_org.mov?dl=1

Do notice how after painfully loading up all the text views, UITextView takes it's time to do all the data detection (constantly trying to scroll with my fingers).

**Comment by galambalazs** [comment] 2015-07-01 20:53
here is my quick JSQ fork with the new TTT. 

I have a more advanced version in development, but this is just for a quick look for you guys.

https://www.dropbox.com/s/c92957h65r94vhx/JSQ_with_new_TTT.zip?dl=0

**Comment by galambalazs** [comment] 2015-07-01 21:04
Here is the 1500 labels demo in case you wanted to run it yourself.
(up for grab for anybody else of course :-). 
https://www.dropbox.com/s/1spaavjcrd8r5jq/test_1500_labels_uitextview_vs_new_ttt_for_leo.zip?dl=0

There's no menu, so you just change the `#define` in code to run a UITextView or TTTLabel version.

**Comment by appleguy** [comment] 2015-08-05 00:18
Hey everyone — really inspiring to see the amount of community collaboration going on here!  What a phenomenal example of the iOS OSS community :).

I just wanted to throw it out there that AsyncDisplayKit has added support for automatic layout, and it's working phenomenally well for us at Pinterest.  It is not UIKit Autolayout, which is implemented in an opaque way that prevents it from being optimized, but it is Box Model automatic layout that has gained a decisive favor across the industry.  Box model is used not only by the whole Web & CSS world, but also React Native, ComponentKit, WatchOS, and is also coming to iOS 9 in part with UIStackView.

From having talked to my friends on the iOS & WatchOS teams, they pointed out that "automatic layout" has gone through three major iterations: autoresizing masks, constraints-based auto layout, and box model-style auto layout.  The trend towards box model is clear, both inside and outside of Apple.

Pinterest had been seeing a rapid rise in UIKit Autolayout usage in recent months, and it certainly shows in the app.  It's definitely one of the worst performing apps used by >10M people.  The cost of the layout actually increases exponentially as new constraints are added, and is not just difficult to optimize, but technically impossible to make significant improvements — there's no way to get the constrained size for text labels so that you could do the work asynchronously.  It's a shame, because these problems really do eliminate it as a choice for developers that strive for great performance.  The statistical facts of profiling show that using constraints-based auto layout guarantees you will never achieve ideal performance, so Pinterest recently followed suit and banned Autolayout like Facebook and Instagram.  We as engineers should be angry that Apple promotes a tool with such detrimental performance for any non-trivial use case.

Remember that Apple's tools cater to the very large number of junior developers in the world.  They've always pushed Interface Builder, too — but when I left the iOS team after we developed 5.0, not a single app in the system was built with IB.  I can almost guarantee you that a majority of Apple's 1st-party layout code uses thoughtfully-factored manual layout code.  Manual layout doesn't need to be tedious, fragile, or repetitive.

All that said, ASLayoutSpec is a really fascinating paradigm that I would encourage folks to check out and give feedback on.  Even if you think it's terrible, the community working on it would honestly love the feedback.  I'm not sure ASDK is appropriate for JSQMessagesViewController, but it's certainly cool to realize that ASLayoutSpec allows you to create completely asynchronous, multi-core concurrent layout calculations that are anything from 100% automatic to 100% manual.  It's a hugely empowering feeling to be able to create a custom layout spec and then apply that anywhere in your app, regardless of the content / elements being positioned.  You can take something like the off-the-shelf ASStackLayoutSpec to make a vertical stack of horizontal stacks, and create a flexible grid component without any math.  You can add manual layout code at any level, and caching is fully automatic.

Here's the PR that added it, which you can scroll through to see the box model specific classes; the master branch has a refined version.
https://github.com/facebook/AsyncDisplayKit/pull/468

Let me know if I can help answer any questions you have while optimizing, even without ASDK!  (If you join the group fb.me/paperf8, send me a direct message on Facebook)

**Comment by appleguy** [comment] 2015-08-05 00:21
One last thing — this other project isn't nearly as full featured as JSQMessagesViewController, but for anyone interested at poking at performance, it's a reasonable example of an un-optimized ASDK implementation: https://github.com/nguyenhuy/AsyncMessagesViewController .  Dialing it in with optional optimization features like layer-backing, precompositing, etc would guarantee 60FPS performance on an iPhone 4, but I'm not sure how close that project gets without having focused on profiling.

**Comment by ghazel** [comment] 2015-08-05 02:46
Tremendous work @appleguy.

I would like to say, though, that for JSQ I am skeptical of AsyncDisplayKit. The native iOS Messages app clearly uses UICollectionView directly, and seems to perform great.

**Comment by jessesquires** [comment] 2015-08-05 04:19
Thanks for all the thoughts/feedback @appleguy ! :smile:

**Comment by galambalazs** [comment] 2015-08-05 07:30
@appleguy great progress with ASDK!


The bottleneck in this project is the **slow `UITextView` rendering & data detecting**.
Anyone interested can try out the TTTAttributedLabel fork of this project:
https://www.dropbox.com/s/c92957h65r94vhx/JSQ_with_new_TTT.zip?dl=0

After that switch it's 60 FPS even with auto layout.
(altough I also have a fork that replaces AL with manual layout, 
but Jesse so far said that he doesn't wanna go that route)


And while it's true that Apple *seemingly* uses `UITextView` inside ChatKit, after carefully reverse engineering their code (I told you I spent a lot of time with this) they are using private APIs, 
one of them being

    - (id)initReadonlyAndUnselectableWithFrame:(CGRect)arg1 textContainer:(NSTextContainer)arg2

...which seems to perform waaaay better than a standard `UITextView` that has `selectable` and `editable` properties set *after* the init.

Now why this is private API I don't know, but doing my 1500 labels demo with it shows the difference
(altough TTT is still clearly faster).

**Comment by Allenn** [comment] 2015-08-06 17:43
Hi all,
First I would like to give my thanks to @jessesquires for this project and how you try to keep it up to date, and also to @galambalazs for his fixes for AL (your PR is still not added to develop, IMO it should be).

@galambalazs did you make a new version of JSQ with TTT or is the dropbox link your last try ? Don't you have a fork or a branch for this purpose ? For now, I'm on a fork of a swift-based-chat which use JSQ but I use cocoapod to get the version you did with the AL iOS 8 fixes and I would like to switch to the TTT version properly (so with pods my case). Will you do it or will wait for @jessesquires to update the project ?

**Comment by galambalazs** [comment] 2015-08-06 21:29
@Allenn I have a local TTT branch, but it hasn't been pushed to github yet.

There's one main thing that sets TTT apart from UITextView: it supports data detectors, but doesn't provide the default actions that UITextView has.

I have an emulation layer which basically uses a dummy UITextView to simulate the default actions, but I didn't have time to finish it 100%.

Other than that TTT is pretty solid per my testing.

I'm still waiting for Jesse to decide what's the plan for 8.0


If TTT doesn't make it to this repo, I'll publish a 8.0 + TTT fork for sure. :)

**Comment by jessesquires** [comment] 2016-01-20 21:16
### Update:

Hello all. I know things have been moving slowly on this front. Sorry. :grin: 

The official plan is to move to `TTTAttributedLabel`(#1337) for the 8.0 release. (#1216)

**Comment by galambalazs** [comment] 2016-01-21 08:36
@jessesquires awesome news!

**Comment by thakurdDev** [comment] 2016-04-07 07:04
In IOS 7 scrolling was working perfect but above IOS 7 scrolling is choopy 
and i found a solution for that 
Use Below Method in your custom UICollectionview Cell 

- (UICollectionViewLayoutAttributes *)preferredLayoutAttributesFittingAttributes:(UICollectionViewLayoutAttributes *)layoutAttributes
{
    return layoutAttributes;
}

**Comment by appleios** [comment] 2016-04-22 11:09
@thakurdDev it will still have this little jitters, even with this "optimization".

Seems that you can avoid jitters when using autolatout (I've created a simple collection view with bubbles and it jitters when bubbles should be resized from bigger to smaller or vice versa; on low scroll speed as described by @galambalazs). Manual layout is not an easy thing to implement correctly, but smooth scroll deserves the efforts.

**Comment by vishnuag05** [comment] 2016-06-02 11:08
Seriously autolayout sucks , I always wondered whether I am doing something wrong but seems like its a universal problem

**Comment by kuyazee** [comment] 2016-06-17 08:26
I'm also running on iphone5s and it lags so much when I scroll up or down

**Comment by ippily** [comment] 2016-07-14 11:57
Has there been any updates on this? On iPhone 5 it is seriously laggy and iPhone 6 it is slightly better
