### ISSUE TITLE
Auto property synthesis will not synthesize property 'dataSource'; it will be implemented by its superclass, use @dynamic to acknowledge intention

### ISSUE THREAD

**Issue by datomnurdin** [jessesquires/JSQMessagesViewController#963] opened 2015-05-05 13:29 UTC
I got this warning message after update latest pod.

```
/Users/MNurdin/Documents/iOS/xxxxx/Pods/JSQMessagesViewController/JSQMessagesViewController/Views/JSQMessagesCollectionView.h:40:69: Auto property synthesis will not synthesize property 'dataSource'; it will be implemented by its superclass, use @dynamic to acknowledge intention
```

Code

```
@property (weak, nonatomic) id<JSQMessagesCollectionViewDataSource> dataSource;
```

Please advice. Thank you.

**Comment by jessesquires** [comment] 2015-05-05 15:00
fixed in 7.0.1. duplicate of #828 

please do not open duplicate issues.

**Closed by jessesquires** 2015-05-05 15:00 UTC
