### ISSUE TITLE
Have chat message text align LTR / RTL based on the language of the message text

### ISSUE THREAD

**Issue by ebbe-brandstrup** [jessesquires/JSQMessagesViewController#1107] opened 2015-07-22 12:09 UTC
Firstly, thanks for this awesome project!

I'm working on a project that requires some more RTL support. Having the text alignment of text inside the message bubbles respect the language of the text is one of those things (because some of our users use both RTL and LTR languages within the same chat conversation).

Browsing through the current issues and PRs I noticed that PR #1009 adds support for this. @jessesquires, could you please consider merging that PR?

Best regards,
Ebbe

**Comment by jessesquires** [comment] 2015-07-23 05:07
Thanks @ebbe-brandstrup !

I'm going to close this as a duplicate of #611 and #1009. 

In the meantime, you can apply the patch in #1009 to your own fork.

**Closed by jessesquires** 2015-07-23 05:07 UTC
Labels: duplicate, feature request

**Comment by ebbe-brandstrup** [comment] 2015-07-23 07:14
Thanks for the quick reply!

I'll just do that for now.
