### ISSUE TITLE
JSQMessagesViewController/JSQMessages.h file not found

### ISSUE THREAD

**Issue by jerembab** [jessesquires/JSQMessagesViewController#1599] opened 2016-05-25 21:02 UTC
I have an issue when I try to install a pod with Cocoapods , target on iOS 8  (before that the JSQMessagesViewController worked great)  
and using use_frameworks!

In my podfile:
platform :ios, '8.0'
use_frameworks!

target '...' do
pod 'Firebase', '>= 2.5.0'
pod 'JSQMessagesViewController', '~> 7.2'
...

I run the command "pod install" and get the output:
Installing JSQMessagesViewController (7.3.0)
Installing JSQSystemSoundPlayer (2.0.1)

Everything seems to be going well until I run the project, Im getting a build error:

JSQMessagesViewController/JSQMessages.h file not found

<unknown>:0: error: failed to import bridging header '/Users/.../Downloads/..../...-Bridging-Header.h'

I try to remove in my bridging-header the 
#import "JSQMessagesViewController/JSQMessages.h" line  but I get following error like in  #1497 

#import <JSQSystemSoundPlayer/JSQSystemSoundPlayer.h>  JSQSystemSoundPlayer/JSQSystemSoundPlayer.h  file not found 
and 

Could not build Objective-C module ' JSQMessagesViewController '

Any ideas? thanks for your time..

**Comment by jessesquires** [comment] 2016-05-26 03:17
Thanks @jerembab ! This looks like a duplicate of #1586. See if the discussion there is helpful

**Closed by jessesquires** 2016-05-26 03:17 UTC
Labels: duplicate, questions & help
